import React from 'react';

import i18n from '../../localization/i18n';

import { INPUT_FIELD_TYPE, NEXT_FIELD_TEXT } from '../AppConstants';
import { PEN_TIME_BUDGET_KEYS } from '../FormConstants';

//steps
export const initialStep = 1;
export const totalToolSteps = 2;
export const backToolListingStep = 0;

export const PEN_TIME_BUDGET_FIELDS = [
  {
    key: PEN_TIME_BUDGET_KEYS.ANIMALS_IN_PENS,
    placeholder: i18n.t('numberPlaceholder'),
    label: i18n.t('animalsInPen'),
    inputRef: React.createRef(),
    fieldType: INPUT_FIELD_TYPE.INPUT,
    returnKeyType: NEXT_FIELD_TEXT.NEXT,
    minValue: 0,
    maxValue: 99999,
    required: false,
    hasCommas: true,
    isInteger: true,
  },
  {
    key: PEN_TIME_BUDGET_KEYS.NO_OF_STALLS,
    placeholder: i18n.t('numberPlaceholder'),
    label: i18n.t('number_of_stalls'),
    inputRef: React.createRef(),
    fieldType: INPUT_FIELD_TYPE.INPUT,
    returnKeyType: NEXT_FIELD_TEXT.NEXT,
    minValue: 0,
    maxValue: 999,
    required: false,
    hasCommas: false,
    isInteger: true,
  },
  {
    key: PEN_TIME_BUDGET_KEYS.WALKING_TIME_TO_PARLOR,
    placeholder: i18n.t('decimalNumberPlaceholder'),
    label: i18n.t('walkingTimeToParlor'),
    customLabel: true,
    inputRef: React.createRef(),
    fieldType: INPUT_FIELD_TYPE.INPUT,
    returnKeyType: NEXT_FIELD_TEXT.NEXT,
    minValue: 0,
    maxValue: 24,
    decimalPoints: 2,
    isInteger: false,
    required: false,
    hasCommas: false,
  },
  {
    key: PEN_TIME_BUDGET_KEYS.TIME_IN_PARLOR,
    placeholder: i18n.t('decimalNumberPlaceholder'),
    label: i18n.t('timeInParlor'),
    customLabel: true,
    inputRef: React.createRef(),
    fieldType: INPUT_FIELD_TYPE.INPUT,
    returnKeyType: NEXT_FIELD_TEXT.NEXT,
    minValue: 0,
    maxValue: 24,
    decimalPoints: 2,
    isInteger: false,
    required: false,
  },
  {
    key: PEN_TIME_BUDGET_KEYS.WALKING_TIME_FROM_PARLOR,
    placeholder: i18n.t('decimalNumberPlaceholder'),
    label: i18n.t('walkingTimeFromParlors'),
    customLabel: true,
    inputRef: React.createRef(),
    fieldType: INPUT_FIELD_TYPE.INPUT,
    returnKeyType: NEXT_FIELD_TEXT.NEXT,
    minValue: 0,
    maxValue: 24,
    decimalPoints: 2,
    isInteger: false,
    required: false,
  },
  {
    key: PEN_TIME_BUDGET_KEYS.MILKING_FREQUENCY,
    placeholder: i18n.t('singleDecimalNumberPlaceholder'),
    label: i18n.t('milkingFrequency'),
    customLabel: true,
    inputRef: React.createRef(),
    fieldType: INPUT_FIELD_TYPE.INPUT,
    returnKeyType: NEXT_FIELD_TEXT.NEXT,
    minValue: 0,
    maxValue: 9,
    decimalPoints: 1,
    isInteger: false,
    required: false,
  },
  {
    key: PEN_TIME_BUDGET_KEYS.TOTAL_STALLS_IN_PARLOR,
    placeholder: i18n.t('numberPlaceholder'),
    label: i18n.t('totalStallsInParlor'),
    customLabel: true,
    inputRef: React.createRef(),
    fieldType: INPUT_FIELD_TYPE.INPUT,
    returnKeyType: NEXT_FIELD_TEXT.NEXT,
    minValue: 0,
    maxValue: 999,
    isInteger: true,
    required: false,
  },
  {
    key: PEN_TIME_BUDGET_KEYS.TIME_IN_LOCK_UP,
    placeholder: i18n.t('decimalNumberPlaceholder'),
    label: i18n.t('timeInLockUp'),
    customLabel: true,
    inputRef: React.createRef(),
    fieldType: INPUT_FIELD_TYPE.INPUT,
    returnKeyType: NEXT_FIELD_TEXT.NEXT,
    minValue: 0,
    maxValue: 24,
    decimalPoints: 2,
    required: false,
    isInteger: false,
  },
  {
    key: PEN_TIME_BUDGET_KEYS.OTHER_NON_REST_TIME,
    placeholder: i18n.t('decimalNumberPlaceholder'),
    label: i18n.t('otherNonRestTime'),
    customLabel: true,
    inputRef: React.createRef(),
    fieldType: INPUT_FIELD_TYPE.INPUT,
    returnKeyType: NEXT_FIELD_TEXT.NEXT,
    minValue: 0,
    maxValue: 24,
    decimalPoints: 2,
    required: false,
    isInteger: false,
  },
  {
    key: PEN_TIME_BUDGET_KEYS.RESTING_REQUIREMENT,
    placeholder: i18n.t('decimalNumberPlaceholder'),
    label: i18n.t('restingRequirements'),
    inputRef: React.createRef(),
    fieldType: INPUT_FIELD_TYPE.INPUT,
    returnKeyType: NEXT_FIELD_TEXT.NEXT,
    minValue: 0,
    maxValue: 24,
    decimalPoints: 2,
    isInteger: false,
    required: false,
  },
  {
    key: PEN_TIME_BUDGET_KEYS.EATING_TIME,
    placeholder: i18n.t('decimalNumberPlaceholder'),
    label: i18n.t('eatingTime'),
    customLabel: true,
    inputRef: React.createRef(),
    fieldType: INPUT_FIELD_TYPE.INPUT,
    returnKeyType: NEXT_FIELD_TEXT.NEXT,
    minValue: 0,
    maxValue: 24,
    decimalPoints: 2,
    isInteger: false,
    required: false,
  },
  {
    key: PEN_TIME_BUDGET_KEYS.DRINKING_GROOMING_TIME,
    placeholder: i18n.t('decimalNumberPlaceholder'),
    label: i18n.t('drinkingGroomingTime'),
    inputRef: React.createRef(),
    fieldType: INPUT_FIELD_TYPE.INPUT,
    returnKeyType: NEXT_FIELD_TEXT.DONE,
    minValue: 0,
    maxValue: 24,
    decimalPoints: 2,
    isInteger: false,
    required: false,
  },
];

export const PEN_TIME_CATEGORIES = {
  ANIMALS_IN_PENS: 'animalsInPen',
  OVER_CROWDING: 'overCrowding',
  TIME_PER_MILKING: 'timePerMilking',
  PARLOR_TURNS_PER_HOUR: 'parlorTurnsPerHour',
  ANIMALS_MILKED_PER_HOUR: 'animalsMilkedPerHour',
  TOTAL_TIME_MILKING: 'totalTimeMilking',
  WALKING_TO_FIND_STALL: 'walkingToFindStall',
  TOTAL_NON_RESTING_TIME: 'totalNonRestingTime',
  TIME_REMAINING_FOR_RESTING: 'timeRemainingForResting',
  TIME_REQUIRED_FOR_RESTING: 'timeRequiredForResting',
  RESTING_DIFFERENCE: 'restingDifference',
  POTENTIAL_MILK_LOSS_GAIN: 'potentialMilkLossGain',
  ENERGY_CHANGE: 'energyChange',
  BODY_WEIGHT_CHANGE: 'bodyWeightChange',
  BODY_CONDITION_SCORE: 'bodyConditionScoreChange',
};

export const PEN_TIME_BUDGET_GRAPH_TYPES = {
  TIME_AVAILABLE_FOR_RESTING: i18n.t('timeAvailableForResting'),
  POTENTIAL_MILK_LOSS_GAIN: i18n.t('potentialMilkLossGain'),
};

export const PEN_TIME_BUDGET_GRAPHS = [
  {
    id: PEN_TIME_BUDGET_GRAPH_TYPES.TIME_AVAILABLE_FOR_RESTING,
    name: PEN_TIME_BUDGET_GRAPH_TYPES.TIME_AVAILABLE_FOR_RESTING,
  },
  {
    id: PEN_TIME_BUDGET_GRAPH_TYPES.POTENTIAL_MILK_LOSS_GAIN,
    name: PEN_TIME_BUDGET_GRAPH_TYPES.POTENTIAL_MILK_LOSS_GAIN,
  },
];
