export default {
  GET_ANIMALS_REQUEST: 'GET_ANIMALS_REQUEST',
  GET_ANIMALS_SUCCESS: 'GET_ANIMALS_SUCCESS',
  GET_ANIMALS_FAILURE: 'GET_ANIMALS_FAILURE',

  CLEAR_ANIMAL_ANALYSIS_REQUEST: 'CLEAR_ANIMAL_ANALYSIS_REQUEST',
  CLEAR_ANIMAL_ANALYSIS_SUCCESS: 'CLEAR_ANIMAL_ANALYSIS_SUCCESS',
  CLEAR_ANIMAL_ANALYSIS_FAILURE: 'CLEAR_ANIMAL_ANALYSIS_FAILURE',
  RESET_CLEAR_ANIMAL_ANALYSIS_REQUEST: 'RESET_CLEAR_ANIMAL_ANALYSIS_REQUEST',

  CREATE_ANIMAL_REQUEST: 'CREATE_ANIMAL_REQUEST',
  CREATE_ANIMAL_SUCCESS: 'CREATE_ANIMAL_SUCCESS',
  CREATE_ANIMAL_FAILURE: 'CREATE_ANIMAL_FAILURE',
  RESET_CREATE_ANIMAL_REQUEST: 'RESET_CREATE_ANIMAL_REQUEST',

  UPDATE_ANIMAL_REQUEST: 'UPDATE_ANIMAL_REQUEST',
  UPDATE_ANIMAL_SUCCESS: 'UPDATE_ANIMAL_SUCCESS',
  UPDATE_ANIMAL_FAILURE: 'UPDATE_ANIMAL_FAILURE',
  RESET_UPDATE_ANIMAL_REQUEST: 'RESET_UPDATE_ANIMAL_REQUEST',

  DELETE_ANIMAL_REQUEST: 'DELETE_ANIMAL_REQUEST',
  DELETE_ANIMAL_SUCCESS: 'DELETE_ANIMAL_SUCCESS',
  DELETE_ANIMAL_FAILURE: 'DELETE_ANIMAL_FAILURE',
  RESET_DELETE_ANIMAL_REQUEST: 'RESET_DELETE_ANIMAL_REQUEST',
};
