export default {
  // Initialization
  INITIALIZE_CALF_HEIFER_GROWTH_CHARTS_TOOL_REQUEST:
    'INITIALIZE_CALF_HEIFER_GROWTH_CHARTS_TOOL_REQUEST',
  INITIALIZE_CALF_HEIFER_GROWTH_CHARTS_TOOL_SUCCESS:
    'INITIALIZE_CALF_HEIFER_GROWTH_CHARTS_TOOL_SUCCESS',
  INITIALIZE_CALF_HEIFER_GROWTH_CHARTS_TOOL_FAILURE:
    'INITIALIZE_CALF_HEIFER_GROWTH_CHARTS_TOOL_FAILURE',

  // Tab and step navigation
  CHANGE_CALF_HEIFER_GROWTH_CHARTS_TAB: 'CHANGE_CALF_HEIFER_GROWTH_CHARTS_TAB',
  CHANGE_CALF_HEIFER_GROWTH_VIEWING_STEP:
    'CHANGE_CALF_HEIFER_GROWTH_VIEWING_STEP',

  // Settings form
  UPDATE_SETTINGS_FORM_RESULT_BUTTON: 'UPDATE_SETTINGS_FORM_RESULT_BUTTON',
  UPDATE_TOOL_DATA_VALIDATION_STATE: 'UPDATE_TOOL_DATA_VALIDATION_STATE',
  SUBMIT_SETTINGS_FORM_REQUEST: 'SUBMIT_SETTINGS_FORM_REQUEST',
  SUBMIT_SETTINGS_FORM_SUCCESS: 'SUBMIT_SETTINGS_FORM_SUCCESS',
  SUBMIT_SETTINGS_FORM_FAILURE: 'SUBMIT_SETTINGS_FORM_FAILURE',

  // Growth type switching
  SWITCH_CALF_HEIFER_GROWTH_TYPE_REQUEST:
    'SWITCH_CALF_HEIFER_GROWTH_TYPE_REQUEST',
  SWITCH_CALF_HEIFER_GROWTH_TYPE_SUCCESS:
    'SWITCH_CALF_HEIFER_GROWTH_TYPE_SUCCESS',
  SWITCH_CALF_HEIFER_GROWTH_TYPE_FAILURE:
    'SWITCH_CALF_HEIFER_GROWTH_TYPE_FAILURE',

  // Animal CRUD operations
  ADD_CALF_HEIFER_GROWTH_ANIMAL_REQUEST:
    'ADD_CALF_HEIFER_GROWTH_ANIMAL_REQUEST',
  ADD_CALF_HEIFER_GROWTH_ANIMAL_SUCCESS:
    'ADD_CALF_HEIFER_GROWTH_ANIMAL_SUCCESS',
  ADD_CALF_HEIFER_GROWTH_ANIMAL_FAILURE:
    'ADD_CALF_HEIFER_GROWTH_ANIMAL_FAILURE',

  UPDATE_CALF_HEIFER_GROWTH_ANIMAL_REQUEST:
    'UPDATE_CALF_HEIFER_GROWTH_ANIMAL_REQUEST',
  UPDATE_CALF_HEIFER_GROWTH_ANIMAL_SUCCESS:
    'UPDATE_CALF_HEIFER_GROWTH_ANIMAL_SUCCESS',
  UPDATE_CALF_HEIFER_GROWTH_ANIMAL_FAILURE:
    'UPDATE_CALF_HEIFER_GROWTH_ANIMAL_FAILURE',

  DELETE_CALF_HEIFER_GROWTH_ANIMAL_REQUEST:
    'DELETE_CALF_HEIFER_GROWTH_ANIMAL_REQUEST',
  DELETE_CALF_HEIFER_GROWTH_ANIMAL_SUCCESS:
    'DELETE_CALF_HEIFER_GROWTH_ANIMAL_SUCCESS',
  DELETE_CALF_HEIFER_GROWTH_ANIMAL_FAILURE:
    'DELETE_CALF_HEIFER_GROWTH_ANIMAL_FAILURE',

  // Filters
  UPDATE_ANIMAL_FILTERS: 'UPDATE_CALF_HEIFER_GROWTH_ANIMAL_FILTERS',
  RESET_ANIMAL_FILTERS: 'RESET_CALF_HEIFER_GROWTH_ANIMAL_FILTERS',

  GET_CALF_HEIFER_GROWTH_FILTERED_ANIMALS_REQUEST:
    'GET_CALF_HEIFER_GROWTH_FILTERED_ANIMALS_REQUEST',
  GET_CALF_HEIFER_GROWTH_FILTERED_ANIMALS_SUCCESS:
    'GET_CALF_HEIFER_GROWTH_FILTERED_ANIMALS_SUCCESS',
  GET_CALF_HEIFER_GROWTH_FILTERED_ANIMALS_FAILURE:
    'GET_CALF_HEIFER_GROWTH_FILTERED_ANIMALS_FAILURE',

  UPDATE_CALF_HEIFER_TOOL_DATA_REQUEST: 'UPDATE_CALF_HEIFER_TOOL_DATA_REQUEST',

  GET_CALF_HEIFER_GROWTH_SUMMARY_REQUEST:
    'GET_CALF_HEIFER_GROWTH_SUMMARY_REQUEST',
  GET_CALF_HEIFER_GROWTH_SUMMARY_SUCCESS:
    'GET_CALF_HEIFER_GROWTH_SUMMARY_SUCCESS',
  GET_CALF_HEIFER_GROWTH_SUMMARY_FAILURE:
    'GET_CALF_HEIFER_GROWTH_SUMMARY_FAILURE',

  GET_CALF_HEIFER_GROWTH_TARGETS_REQUEST:
    'GET_CALF_HEIFER_GROWTH_TARGETS_REQUEST',
  GET_CALF_HEIFER_GROWTH_TARGETS_SUCCESS:
    'GET_CALF_HEIFER_GROWTH_TARGETS_SUCCESS',
  GET_CALF_HEIFER_GROWTH_TARGETS_FAILURE:
    'GET_CALF_HEIFER_GROWTH_TARGETS_FAILURE',

  GET_CALF_HEIFER_GROWTH_GRAPH_DATA_REQUEST:
    'GET_CALF_HEIFER_GROWTH_GRAPH_DATA_REQUEST',
  GET_CALF_HEIFER_GROWTH_GRAPH_DATA_SUCCESS:
    'GET_CALF_HEIFER_GROWTH_GRAPH_DATA_SUCCESS',
  GET_CALF_HEIFER_GROWTH_GRAPH_DATA_FAILURE:
    'GET_CALF_HEIFER_GROWTH_GRAPH_DATA_FAILURE',

  CHANGE_CALF_HEIFER_GROWTH_VISUALIZATION_OPTION_REQUEST:
    'CHANGE_CALF_HEIFER_GROWTH_VISUALIZATION_OPTION_REQUEST',
  CHANGE_CALF_HEIFER_GROWTH_VISUALIZATION_OPTION_SUCCESS:
    'CHANGE_CALF_HEIFER_GROWTH_VISUALIZATION_OPTION_SUCCESS',
  CHANGE_CALF_HEIFER_GROWTH_VISUALIZATION_OPTION_FAILURE:
    'CHANGE_CALF_HEIFER_GROWTH_VISUALIZATION_OPTION_FAILURE',

  DOWNLOAD_CALF_HEIFER_GROWTH_GRAPH_DATA:
    'DOWNLOAD_CALF_HEIFER_GROWTH_GRAPH_DATA',

  SHARE_CALF_HEIFER_GROWTH_GRAPH_DATA: 'SHARE_CALF_HEIFER_GROWTH_GRAPH_DATA',

  ADD_CALF_HEIFER_RESULT_ANIMAL_REQUEST:
    'ADD_CALF_HEIFER_RESULT_ANIMAL_REQUEST',

  CLEAR_CALF_HEIFER_GROWTH_REDUCER_REQUEST:
    'CLEAR_CALF_HEIFER_GROWTH_REDUCER_REQUEST',
};
