export default {
  INITIALIZE_CALF_HEIFER_SCORECARD_TOOL_REQUEST:
    'INITIALIZE_CALF_HEIFER_SCORECARD_TOOL_REQUEST',
  INITIALIZE_CALF_HEIFER_SCORECARD_TOOL_SUCCESS:
    'INITIALIZE_CALF_HEIFER_SCORECARD_TOOL_SUCCESS',
  INITIALIZE_CALF_HEIFER_SCORECARD_TOOL_FAILURE:
    'INITIALIZE_CALF_HEIFER_SCORECARD_TOOL_FAILURE',

  ACTIVE_QUESTIONS_SECTION: 'ACTIVE_QUESTIONS_SECTION',

  UPDATE_ANSWERED_QUESTION_REQUEST: 'UPDATE_ANSWERED_QUESTION_REQUEST',
  UPDATE_ANSWERED_QUESTION_SUCCESS: 'UPDATE_ANSWERED_QUESTION_SUCCESS',
  UPDATE_ANSWERED_QUESTION_FAILURE: 'UPDATE_ANSWERED_QUESTION_FAILURE',

  SAVE_AND_UPDATE_TOOL_DB_DATA: 'SAVE_AND_UPDATE_TOOL_DB_DATA',

  CLEAR_TOOL_REDUCERS_REQUEST: 'CLEAR_TOOL_REDUCERS_REQUEST',
};
