export default {
  INITIALIZE_CUD_CHEWING_DATA: 'INITIALIZE_CUD_CHEWING_DATA',

  INITIALIZE_DB_CUD_CHEWING: 'INITIALIZE_DB_CUD_CHEWING',

  UPDATE_CUD_CHEWING_GOALS: 'UPDATE_CUD_CHEWING_GOALS',

  SAVE_CUD_CHEWING_DATA: 'SAVE_CUD_CHEWING_DATA',

  ADD_CUD_CHEWING_PEN: 'ADD_CUD_CHEWING_PEN',

  ADD_CUD_CHEWS_COW: 'ADD_CUD_CHEWS_COW',

  UPDATE_CHEWING_COUNT: 'UPDATE_CHEWING_COUNT',

  UPDATE_CHEWS_COUNT: 'UPDATE_CHEWS_COUNT',

  SAVE_RUMEN_HERD_ANALYSIS_REQUEST: 'SAVE_RUMEN_HERD_ANALYSIS_REQUEST',
};
