export default {
  SAVE_HEAT_STRESS_REQUEST: 'SAVE_HEAT_STRESS_REQUEST',
  SAVE_HEAT_STRESS_SUCCESS: 'SAVE_HEAT_STRESS_SUCCESS',
  SAVE_HEAT_STRESS_FAILURE: 'SAVE_HEAT_STRESS_FAILURE',
  RESET_SAVE_HEAT_STRESS_REQUEST: 'RESET_SAVE_HEAT_STRESS_REQUEST',
};
