export default {
  SAVE_MANURE_SCORE_PEN_ANALYSIS_REQUEST:
    'SAVE_MANURE_SCORE_PEN_ANALYSIS_REQUEST',
  SAVE_MANURE_SCORE_PEN_ANALYSIS_SUCCESS:
    'SAVE_MANURE_SCORE_PEN_ANALYSIS_SUCCESS',
  SAVE_MANURE_SCORE_PEN_ANALYSIS_FAILURE:
    'SAVE_MANURE_SCORE_PEN_ANALYSIS_FAILURE',
  RESET_MANURE_SCORE_PEN_ANALYSIS_REQUEST:
    'RESET_MANURE_SCORE_PEN_ANALYSIS_REQUEST',

  SAVE_MANURE_SCORE_HERD_ANALYSIS_REQUEST:
    'SAVE_MANURE_SCORE_HERD_ANALYSIS_REQUEST',
  SAVE_MANURE_SCORE_HERD_ANALYSIS_SUCCESS:
    'SAVE_MANURE_SCORE_HERD_ANALYSIS_SUCCESS',
  SAVE_MANURE_SCORE_HERD_ANALYSIS_FAILURE:
    'SAVE_MANURE_SCORE_HERD_ANALYSIS_FAILURE',

  UPDATE_MANURE_SCORE_HERD_ANALYSIS_REQUEST:
    'UPDATE_MANURE_SCORE_HERD_ANALYSIS_REQUEST',
  UPDATE_MANURE_SCORE_HERD_ANALYSIS_SUCCESS:
    'UPDATE_MANURE_SCORE_HERD_ANALYSIS_SUCCESS',
  UPDATE_MANURE_SCORE_HERD_ANALYSIS_FAILURE:
    'UPDATE_MANURE_SCORE_HERD_ANALYSIS_FAILURE',

  SAVE_MANURE_GOALS_REQUEST: 'SAVE_MANURE_GOALS_REQUEST',
  SAVE_MANURE_GOALS_SUCCESS: 'SAVE_MANURE_GOALS_SUCCESS',
  SAVE_MANURE_GOALS_FAILURE: 'SAVE_MANURE_GOALS_FAILURE',
};
