export default {
  SAVE_MILK_SOLD_EVALUATION_REQUEST: 'SAVE_MILK_SOLD_EVALUATION_REQUEST',
  SAVE_MILK_SOLD_EVALUATION_SUCCESS: 'SAVE_MILK_SOLD_EVALUATION_SUCCESS',
  SAVE_MILK_SOLD_EVALUATION_FAILURE: 'SAVE_MILK_SOLD_EVALUATION_FAILURE',

  CHANGE_ACTIVE_MILK_SOLD_RESULT_TAB: 'CHANGE_ACTIVE_MILK_SOLD_RESULT_TAB',
};
