export default {
  GET_PEN_TIME_BUDGET_ANALYSIS_REQUEST: 'GET_PEN_TIME_BUDGET_ANALYSIS_REQUEST',
  GET_PEN_TIME_BUDGET_ANALYSIS_SUCCESS: 'GET_PEN_TIME_BUDGET_ANALYSIS_SUCCESS',
  GET_PEN_TIME_BUDGET_ANALYSIS_FAILURE: 'GET_PEN_TIME_BUDGET_ANALYSIS_FAILURE',

  GET_UPDATED_PEN_TIME_BUDGET_ANALYSIS_REQUEST:
    'GET_UPDATED_PEN_TIME_BUDGET_ANALYSIS_REQUEST',
  GET_UPDATED_PEN_TIME_BUDGET_ANALYSIS_SUCCESS:
    'GET_UPDATED_PEN_TIME_BUDGET_ANALYSIS_SUCCESS',
  GET_UPDATED_PEN_TIME_BUDGET_ANALYSIS_FAILURE:
    'GET_UPDATED_PEN_TIME_BUDGET_ANALYSIS_FAILURE',

  RESET_PEN_TIME_BUDGET_ANALYSIS_REQUEST:
    'RESET_PEN_TIME_BUDGET_ANALYSIS_REQUEST',

  SAVE_PEN_TIME_BUDGET_ANALYSIS_REQUEST:
    'SAVE_PEN_TIME_BUDGET_ANALYSIS_REQUEST',
  SAVE_PEN_TIME_BUDGET_ANALYSIS_SUCCESS:
    'SAVE_PEN_TIME_BUDGET_ANALYSIS_SUCCESS',
  SAVE_PEN_TIME_BUDGET_ANALYSIS_FAILURE:
    'SAVE_PEN_TIME_BUDGET_ANALYSIS_FAILURE',
};
