export default {
  CHANGE_ACCORDION_FORM: 'CHANGE_ACCORDION_FORM',

  UPDATE_RESULT_BUTTON_REQUEST: 'UPDATE_RESULT_BUTTON_REQUEST',

  CHANGE_TOOL_FORM_BODY: 'CHANGE_TOOL_FORM_BODY',

  SAVE_OR_UPDATE_TOOL_DATA_REQUEST: 'SAVE_OR_UPDATE_TOOL_DATA_REQUEST',

  VALIDATE_SITE_SETUP_FIELDS_REQUEST: 'VALIDATE_SITE_SETUP_FIELDS_REQUEST',
  VALIDATE_SITE_SETUP_FIELDS_SUCCESS: 'VALIDATE_SITE_SETUP_FIELDS_SUCCESS',
  VALIDATE_SITE_SETUP_FIELDS_FAILURE: 'VALIDATE_SITE_SETUP_FIELDS_FAILURE',

  UPDATE_SITE_SETUP_DATA: 'UPDATE_SITE_SETUP_DATA',

  CHANGE_PROFITABILITY_RESULTS_TAB: 'CHANGE_PROFITABILITY_RESULTS_TAB',

  SET_PROFITABILITY_COMPARE_VISITS: 'SET_PROFITABILITY_COMPARE_VISITS',

  RESET_TOOL_DEFAULT: 'RESET_TOOL_DEFAULT',

  SET_PROFITABILITY_TOOL_DATA_FOR_OUTPUT:
    'SET_PROFITABILITY_TOOL_DATA_FOR_OUTPUT',

  DOWNLOAD_PROFITABILITY_GRAPH_REQUEST: 'DOWNLOAD_PROFITABILITY_GRAPH_REQUEST',

  SHARE_PROFITABILITY_GRAPH_REQUEST: 'SHARE_PROFITABILITY_GRAPH_REQUEST',
};
