export default {
  UPDATE_ROF_RESULT_BUTTON: 'UPDATE_ROF_RESULT_BUTTON',

  SAVE_OR_UPDATE_ROF_DATA_REQUEST: 'SAVE_OR_UPDATE_ROF_DATA_REQUEST',
  SAVE_OR_UPDATE_ROF_DATA_SUCCESS: 'SAVE_OR_UPDATE_ROF_DATA_SUCCESS',
  SAVE_OR_UPDATE_ROF_DATA_FAILURE: 'SAVE_OR_UPDATE_ROF_DATA_FAILURE',

  //#region rofPrice list
  GET_ROF_PRICE_LIST_REQUEST: 'GET_ROF_PRICE_LIST_REQUEST',
  GET_ROF_PRICE_LIST_SUCCESS: 'GET_ROF_PRICE_LIST_SUCCESS',
  GET_ROF_PRICE_LIST_FAILURE: 'GET_ROF_PRICE_LIST_FAILURE',

  SYNC_ROF_PRICE_LIST_REQUEST: 'SYNC_ROF_PRICE_LIST_REQUEST',
  SYNC_ROF_PRICE_LIST_SUCCESS: 'SYNC_ROF_PRICE_LIST_SUCCESS',
  SYNC_ROF_PRICE_LIST_FAILURE: 'SYNC_ROF_PRICE_LIST_FAILURE',
  //#endregion

  GET_ROF_SUMMARY_REQUEST: 'GET_ROF_SUMMARY_REQUEST',
  GET_ROF_SUMMARY_SUCCESS: 'GET_ROF_SUMMARY_SUCCESS',
  GET_ROF_SUMMARY_FAILURE: 'GET_ROF_SUMMARY_FAILURE',

  CHANGE_ACTIVE_RESULT_TAB: 'CHANGE_ACTIVE_RESULT_TAB',

  CHANGE_COMPARING_ROF_VISITS: 'CHANGE_COMPARING_ROF_VISITS',

  SET_IS_SITE_DATA_UPDATED: 'SET_IS_SITE_DATA_UPDATED',

  RESET_ROF_STATE_TO_DEFAULT: 'RESET_ROF_STATE_TO_DEFAULT',

  SHARE_ROF_GRAPH_REQUEST: 'SHARE_ROF_GRAPH_REQUEST',
  DOWNLOAD_ROF_GRAPH_REQUEST: 'DOWNLOAD_ROF_GRAPH_REQUEST',

  GET_PREVIOUS_ROF_VISIT_DATA_REQUEST: 'GET_PREVIOUS_ROF_VISIT_DATA_REQUEST',
  GET_PREVIOUS_ROF_VISIT_DATA_SUCCESS: 'GET_PREVIOUS_ROF_VISIT_DATA_SUCCESS',
  GET_PREVIOUS_ROF_VISIT_DATA_FAILURE: 'GET_PREVIOUS_ROF_VISIT_DATA_FAILURE',
};
