export default {
  SAVE_RUMEN_FILL_SCORE_PEN_ANALYSIS_REQUEST:
    'SAVE_RUMEN_FILL_SCORE_PEN_ANALYSIS_REQUEST',
  SAVE_RUMEN_FILL_SCORE_PEN_ANALYSIS_SUCCESS:
    'SAVE_RUMEN_FILL_SCORE_PEN_ANALYSIS_SUCCESS',
  SAVE_RUMEN_FILL_SCORE_PEN_ANALYSIS_FAILURE:
    'SAVE_RUMEN_FILL_SCORE_PEN_ANALYSIS_FAILURE',

  SAVE_RUMEN_FILL_GOALS_REQUEST: 'SAVE_RUMEN_FILL_GOALS_REQUEST',
  SAVE_RUMEN_FILL_GOALS_SUCCESS: 'SAVE_RUMEN_FILL_GOALS_SUCCESS',
  SAVE_RUMEN_FILL_GOALS_FAILURE: 'SAVE_RUMEN_FILL_GOALS_FAILURE',

  SAVE_RUMEN_FILL_SCORE_HERD_ANALYSIS_REQUEST:
    'SAVE_RUMEN_FILL_SCORE_HERD_ANALYSIS_REQUEST',
  SAVE_RUMEN_FILL_SCORE_HERD_ANALYSIS_SUCCESS:
    'SAVE_RUMEN_FILL_SCORE_HERD_ANALYSIS_SUCCESS',
  SAVE_RUMEN_FILL_SCORE_HERD_ANALYSIS_FAILURE:
    'SAVE_RUMEN_FILL_SCORE_HERD_ANALYSIS_FAILURE',

  UPDATE_RUMEN_FILL_SCORE_HERD_ANALYSIS_REQUEST:
    'UPDATE_RUMEN_FILL_SCORE_HERD_ANALYSIS_REQUEST',
  UPDATE_RUMEN_FILL_SCORE_HERD_ANALYSIS_SUCCESS:
    'UPDATE_RUMEN_FILL_SCORE_HERD_ANALYSIS_SUCCESS',
  UPDATE_RUMEN_FILL_SCORE_HERD_ANALYSIS_FAILURE:
    'UPDATE_RUMEN_FILL_SCORE_HERD_ANALYSIS_FAILURE',
};
