export default {
  GET_ACCOUNT_REQUEST: 'GET_ACCOUNT_REQUEST',
  GET_ACCOUNT_SUCCESS: 'GET_ACCOUNT_SUCCESS',
  GET_ACCOUNT_FAILURE: 'GET_ACCOUNT_FAILURE',

  ACCOUNT_LIST_RESET: 'ACCOUNT_LIST_RESET',
  ACCOUNT_RESET_FILTER: 'ACCOUNT_RESET_FILTER',

  RESET_ACCOUNT_DETAIL: 'RESET_ACCOUNT_DETAIL',

  GET_ALL_ACCOUNT_REQUEST: 'GET_ALL_ACCOUNT_REQUEST',
  GET_ALL_ACCOUNT_SUCCESS: 'GET_ALL_ACCOUNT_SUCCESS',
  GET_ALL_ACCOUNT_FAILURE: 'GET_ALL_ACCOUNT_FAILURE',
};
