export default {
  GET_ANIMAL_CLASS_REQUEST: 'GET_ANIMAL_CLASS_REQUEST',
  GET_ANIMAL_CLASS_SUCCESS: 'GET_ANIMAL_CLASS_SUCCESS',
  GET_ANIMAL_CLASS_FAILURE: 'GET_ANIMAL_CLASS_FAILURE',

  SYNC_ANIMAL_CLASS_REQUEST: 'SYNC_ANIMAL_CLASS_REQUEST',
  SYNC_ANIMAL_CLASS_SUCCESS: 'SYNC_ANIMAL_CLASS_SUCCESS',
  SYNC_ANIMAL_CLASS_FAILURE: 'SYNC_ANIMAL_CLASS_FAILURE',
};
