export default {
  GET_INITIALIZED_REQUEST: 'GET_INITIALIZED_REQUEST',
  GET_INITIALIZED_SUCCESS: 'GET_INITIALIZED_SUCCESS',
  GET_INITIALIZED_FAILURE: 'GET_INITIALIZED_FAILURE',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  OKTA_LOGIN_REQUEST: 'OKTA_LOGIN_REQUEST',
  OKTA_LOGIN_SUCCESS: 'OKTA_LOGIN_SUCCESS',
  OKTA_LOGIN_FAILURE: 'OKTA_LOGIN_FAILURE',

  AZURE_AD_LOGIN_REQUEST: 'AZURE_AD_LOGIN_REQUEST',
  AZURE_AD_LOGIN_SUCCESS: 'AZURE_AD_LOGIN_SUCCESS',
  AZURE_AD_LOGIN_FAILURE: 'AZURE_AD_LOGIN_FAILURE',

  SET_ONBOARDING: 'SET_ONBOARDING',
  SET_EULA_ACCEPTED: 'SET_EULA_ACCEPTED',

  LOGOUT_REQUESTED: 'LOGOUT_REQUESTED',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};
