export default {
  SYNC_CUSTOMER_REQUEST: 'SYNC_CUSTOMER_REQUEST',
  SYNC_CUSTOMER_SUCCESS: 'SYNC_CUSTOMER_SUCCESS',
  SYNC_CUSTOMER_FAILURE: 'SYNC_CUSTOMER_FAILURE',

  GET_CUSTOMER_BY_ID_REQUEST: 'GET_CUSTOMER_BY_ID_REQUEST',
  GET_CUSTOMER_BY_ID_SUCCESS: 'GET_CUSTOMER_BY_ID_SUCCESS',
  GET_CUSTOMER_BY_ID_FAILURE: 'GET_CUSTOMER_BY_ID_FAILURE',

  UPDATE_CUSTOMER_REQUEST: 'UPDATE_CUSTOMER_REQUEST',
  UPDATE_CUSTOMER_SUCCESS: 'UPDATE_CUSTOMER_SUCCESS',
  UPDATE_CUSTOMER_FAILURE: 'UPDATE_CUSTOMER_FAILURE',

  PUSH_UPDATED_CUSTOMERS_REQUEST: 'PUSH_UPDATED_CUSTOMERS_REQUEST',
  PUSH_UPDATED_CUSTOMERS_SUCCESS: 'PUSH_UPDATED_CUSTOMERS_SUCCESS',
  PUSH_UPDATED_CUSTOMERS_FAILURE: 'PUSH_UPDATED_CUSTOMERS_FAILURE',

  RESET_UPDATE_CUSTOMER_REQUEST: 'RESET_UPDATE_CUSTOMER_REQUEST',

  GET_CUSTOMER_BY_LOCAL_OR_SERVER_ID_REQUEST:
    'GET_CUSTOMER_BY_LOCAL_OR_SERVER_ID_REQUEST',
  GET_CUSTOMER_BY_LOCAL_OR_SERVER_ID_SUCCESS:
    'GET_CUSTOMER_BY_LOCAL_OR_SERVER_ID_SUCCESS',
  GET_CUSTOMER_BY_LOCAL_OR_SERVER_ID_FAILURE:
    'GET_CUSTOMER_BY_LOCAL_OR_SERVER_ID_FAILURE',
};
