export default {
  GET_PINNED_CONTACTS_REQUEST: 'GET_PINNED_CONTACT_REQUEST',
  GET_PINNED_CONTACTS_SUCCESS: 'GET_PINNED_CONTACT_SUCCESS',
  GET_PINNED_CONTACTS_FAILURE: 'GET_PINNED_CONTACT_FAILURE',

  GET_RECENT_IN_PROGRESS_VISIT_REQUEST: 'GET_RECENT_IN_PROGRESS_VISIT_REQUEST',
  GET_RECENT_IN_PROGRESS_VISIT_SUCCESS: 'GET_RECENT_IN_PROGRESS_VISIT_SUCCESS',
  GET_RECENT_IN_PROGRESS_VISIT_FAILURE: 'GET_RECENT_IN_PROGRESS_VISIT_FAILURE',

  GET_NOTEBOOK_ACTION_ITEM_REQUEST: 'GET_NOTEBOOK_ACTION_ITEM_REQUEST',
  GET_NOTEBOOK_ACTION_ITEM_SUCCESS: 'GET_NOTEBOOK_ACTION_ITEM_SUCCESS',
  GET_NOTEBOOK_ACTION_ITEM_FAILURE: 'GET_NOTEBOOK_ACTION_ITEM_FAILURE',

  NAVIGATE_TO_NOTEBOOK_REQUEST: 'NAVIGATE_TO_NOTEBOOK_REQUEST',
  RESET_NAVIGATE_TO_NOTEBOOK_REQUEST: 'RESET_NAVIGATE_TO_NOTEBOOK_REQUEST',

  NAVIGATE_TO_HISTORY_REQUEST: 'NAVIGATE_TO_HISTORY_REQUEST',
  RESET_NAVIGATE_TO_HISTORY_REQUEST: 'RESET_NAVIGATE_TO_HISTORY_REQUEST',

  GET_SYNC_ERRORS_REQUEST: 'GET_SYNC_ERRORS_REQUEST',
  GET_SYNC_ERRORS_SUCCESS: 'GET_SYNC_ERRORS_SUCCESS',
  GET_SYNC_ERRORS_FAILURE: 'GET_SYNC_ERRORS_FAILURE',

  GET_DASHBOARD_NOTIFICATION_REQUEST: 'GET_DASHBOARD_NOTIFICATION_REQUEST',
  GET_DASHBOARD_NOTIFICATION_SUCCESS: 'GET_DASHBOARD_NOTIFICATION_SUCCESS',
  GET_DASHBOARD_NOTIFICATION_FAILURE: 'GET_DASHBOARD_NOTIFICATION_FAILURE',
};
