export default {
  SYNC_DATA_BLOCKING_REQUEST: 'SYNC_DATA_BLOCKING_REQUEST',
  SYNC_DATA_BLOCKING_SUCCESS: 'SYNC_DATA_BLOCKING_SUCCESS',
  SYNC_DATA_BLOCKING_FAILURE: 'SYNC_DATA_BLOCKING_FAILURE',

  SYNC_DATA_NON_BLOCKING_REQUEST: 'SYNC_DATA_NON_BLOCKING_REQUEST',
  SYNC_DATA_NON_BLOCKING_SUCCESS: 'SYNC_DATA_NON_BLOCKING_SUCCESS',
  SYNC_DATA_NON_BLOCKING_FAILURE: 'SYNC_DATA_NON_BLOCKING_FAILURE',

  SYNC_DATA_MANUALLY_REQUEST: 'SYNC_DATA_MANUALLY_REQUEST',
  SYNC_DATA_MANUALLY_SUCCESS: 'SYNC_DATA_MANUALLY_SUCCESS',
  SYNC_DATA_MANUALLY_FAILURE: 'SYNC_DATA_MANUALLY_FAILURE',

  POST_PENDING_DATA_REQUEST: 'POST_PENDING_DATA_REQUEST',
  POST_PENDING_DATA_SUCCESS: 'POST_PENDING_DATA_SUCCESS',
  POST_PENDING_DATA_FAILURE: 'POST_PENDING_DATA_FAILURE',

  GET_UNSYNCED_ITEMS_COUNT_REQUEST: 'GET_UNSYNCED_ITEMS_COUNT_REQUEST',
  GET_UNSYNCED_ITEMS_COUNT_SUCCESS: 'GET_UNSYNCED_ITEMS_COUNT_SUCCESS',
  GET_UNSYNCED_ITEMS_COUNT_FAILURE: 'GET_UNSYNCED_ITEMS_COUNT_FAILURE',

  CANCEL_SYNC: 'CANCEL_SYNC',
  
  UPDATE_MIGRATION_DATA_VERSION_4: 'UPDATE_MIGRATION_DATA_VERSION_4',

};
