export default {
  SYNC_MAX_DAIRY_DIETS_REQUEST: 'SYNC_MAX_DAIRY_DIETS_REQUEST',
  SYNC_MAX_DAIRY_DIETS_SUCCESS: 'SYNC_MAX_DAIRY_DIETS_SUCCESS',
  SYNC_MAX_DAIRY_DIETS_FAILURE: 'SYNC_MAX_DAIRY_DIETS_FAILURE',

  GET_MAX_DAIRY_DIETS_BY_SITE_ID_REQUEST:
    'GET_MAX_DAIRY_DIETS_BY_SITE_ID_REQUEST',
  GET_MAX_DAIRY_DIETS_BY_SITE_ID_SUCCESS:
    'GET_MAX_DAIRY_DIETS_BY_SITE_ID_SUCCESS',
  GET_MAX_DAIRY_DIETS_BY_SITE_ID_FAILURE:
    'GET_MAX_DAIRY_DIETS_BY_SITE_ID_FAILURE',
};
