export default {
  SYNC_EAR_TAGS_REQUEST: 'SYNC_EAR_TAGS_REQUEST',
  SYNC_EAR_TAGS_SUCCESS: 'SYNC_EAR_TAGS_SUCCESS',
  SYNC_EAR_TAGS_FAILURE: 'SYNC_EAR_TAGS_FAILURE',

  GET_EAR_TAGS_REQUEST: 'GET_EAR_TAGS_REQUEST',
  GET_EAR_TAGS_SUCCESS: 'GET_EAR_TAGS_SUCCESS',
  GET_EAR_TAGS_FAILURE: 'GET_EAR_TAGS_FAILURE',
  RESET_GET_EAR_TAGS_REQUEST: 'RESET_GET_EAR_TAGS_REQUEST',

  GET_UNFILTERED_EAR_TAGS_REQUEST: 'GET_UNFILTERED_EAR_TAGS_REQUEST',
  GET_UNFILTERED_EAR_TAGS_SUCCESS: 'GET_UNFILTERED_EAR_TAGS_SUCCESS',
  GET_UNFILTERED_EAR_TAGS_FAILURE: 'GET_UNFILTERED_EAR_TAGS_FAILURE',
  RESET_GET_UNFILTERED_EAR_TAGS_REQUEST:
    'RESET_GET_UNFILTERED_EAR_TAGS_REQUEST',

  CREATE_EAR_TAG_REQUEST: 'CREATE_EAR_TAG_REQUEST',
  CREATE_EAR_TAG_SUCCESS: 'CREATE_EAR_TAG_SUCCESS',
  CREATE_EAR_TAG_FAILURE: 'CREATE_EAR_TAG_FAILURE',
  RESET_CREATE_EAR_TAG_REQUEST: 'RESET_CREATE_EAR_TAG_REQUEST',

  PUSH_ADDED_EAR_TAGS_REQUEST: 'PUSH_ADDED_EAR_TAGS_REQUEST',
  PUSH_ADDED_EAR_TAGS_SUCCESS: 'PUSH_ADDED_EAR_TAGS_SUCCESS',
  PUSH_ADDED_EAR_TAGS_FAILURE: 'PUSH_ADDED_EAR_TAGS_FAILURE',
};
