export default {
  GET_ENUM_REQUEST: 'GET_ENUM_REQUEST',
  GET_ENUM_SUCCESS: 'GET_ENUM_SUCCESS',
  GET_ENUM_FAILURE: 'GET_ENUM_FAILURE',

  SYNC_ENUM_REQUEST: 'SYNC_ENUM_REQUEST',
  SYNC_ENUM_SUCCESS: 'SYNC_ENUM_SUCCESS',
  SYNC_ENUM_FAILURE: 'SYNC_ENUM_FAILURE',

  GET_MULTILINGUAL_ENUM_REQUEST: 'GET_MULTILINGUAL_ENUM_REQUEST',
  GET_MULTILINGUAL_ENUM_SUCCESS: 'GET_MULTILINGUAL_ENUM_SUCCESS',
  GET_MULTILINGUAL_ENUM_FAILURE: 'GET_MULTILINGUAL_ENUM_FAILURE',
};
