export default {
  GENERATE_EXPORT_LOGS_REQUEST: 'GENERATE_EXPORT_LOGS_REQUEST',
  GENERATE_EXPORT_LOGS_SUCCESS: 'GENERATE_EXPORT_LOGS_SUCCESS',
  GENERATE_EXPORT_LOGS_FAILURE: 'GENERATE_EXPORT_LOGS_FAILURE',
  RESET_GENERATE_EXPORT_LOGS_REQUEST: 'RESET_GENERATE_EXPORT_LOGS_REQUEST',
};
