export default {
  INITIALIZE_FORAGE_SCORE_CARD: 'INITIALIZE_FORAGE_SCORE_CARD',

  SELECTED_SILAGE_DATA: 'SELECTED_SILAGE_DATA',

  UPDATE_SILAGE_QUESTIONS: 'UPDATE_SILAGE_QUESTIONS',

  RESTORE_FORAGE_AUDIT_SCORECARD: 'RESTORE_FORAGE_AUDIT_SCORECARD',

  SAVE_FORAGE_AUDIT_SCORECARD_DB: 'SAVE_FORAGE_AUDIT_SCORECARD_DB',

  CLEAR_FORAGE_AUDIT_SCORECARD_REDUCER: 'CLEAR_FORAGE_AUDIT_SCORECARD_REDUCER',

  UPDATE_FORAGE_AUDIT_SCORECARD: 'UPDATE_FORAGE_AUDIT_SCORECARD',

};
