export default {
  GET_COUNTRIES_REQUEST: 'GET_COUNTRIES_REQUEST',
  GET_COUNTRIES_SUCCESS: 'GET_COUNTRIES_SUCCESS',
  GET_COUNTRIES_FAILURE: 'GET_COUNTRIES_FAILURE',

  SYNC_COUNTRIES_REQUEST: 'SYNC_COUNTRIES_REQUEST',
  SYNC_COUNTRIES_SUCCESS: 'SYNC_COUNTRIES_SUCCESS',
  SYNC_COUNTRIES_FAILURE: 'SYNC_COUNTRIES_FAILURE',

  GET_STATES_REQUEST: 'GET_STATES_REQUEST',
  GET_STATES_SUCCESS: 'GET_STATES_SUCCESS',
  GET_STATES_FAILURE: 'GET_STATES_FAILURE',

  SYNC_STATES_REQUEST: 'SYNC_STATES_REQUEST',
  SYNC_STATES_SUCCESS: 'SYNC_STATES_SUCCESS',
  SYNC_STATES_FAILURE: 'SYNC_STATES_FAILURE',

  GET_CITIES_REQUEST: 'GET_CITIES_REQUEST',
  GET_CITIES_SUCCESS: 'GET_CITIES_SUCCESS',
  GET_CITIES_FAILURE: 'GET_CITIES_FAILURE',

  SYNC_CITIES_REQUEST: 'SYNC_CITIES_REQUEST',
  SYNC_CITIES_SUCCESS: 'SYNC_CITIES_SUCCESS',
  SYNC_CITIES_FAILURE: 'SYNC_CITIES_FAILURE',
};
