export default {
  GET_NOTEBOOK_TRAIL_DATA_REQUEST: 'GET_NOTEBOOK_TRAIL_DATA_REQUEST',
  GET_NOTEBOOK_TRAIL_DATA_SUCCESS: 'GET_NOTEBOOK_TRAIL_DATA_SUCCESS',
  GET_NOTEBOOK_TRAIL_DATA_FAILURE: 'GET_NOTEBOOK_TRAIL_DATA_FAILURE',

  GET_NOTEBOOK_REQUEST: 'GET_NOTEBOOK_REQUEST',
  GET_NOTEBOOK_SUCCESS: 'GET_NOTEBOOK_SUCCESS',
  GET_NOTEBOOK_FAILURE: 'GET_NOTEBOOK_FAILURE',

  GET_NOTEBOOK_ACTION_TYPE_LIST_REQUEST:
    'GET_NOTEBOOK_ACTION_TYPE_LIST_REQUEST',
  GET_NOTEBOOK_ACTION_TYPE_LIST_SUCCESS:
    'GET_NOTEBOOK_ACTION_TYPE_LIST_SUCCESS',
  GET_NOTEBOOK_ACTION_TYPE_LIST_FAILURE:
    'GET_NOTEBOOK_ACTION_TYPE_LIST_FAILURE',

  SYNC_NOTEBOOK_REQUEST: 'SYNC_NOTEBOOK_REQUEST',
  SYNC_NOTEBOOK_SUCCESS: 'SYNC_NOTEBOOK_SUCCESS',
  SYNC_NOTEBOOK_FAILURE: 'SYNC_NOTEBOOK_FAILURE',

  NOTEBOOK_LIST_RESET: 'NOTEBOOK_LIST_RESET',
  NOTEBOOK_RESET_FILTER: 'NOTEBOOK_RESET_FILTER',

  GET_VISIT_FOR_ACCOUNT_SITE_REQUEST: 'GET_VISIT_FOR_ACCOUNT_SITE_REQUEST',
  GET_VISIT_FOR_ACCOUNT_SITE_SUCCESS: 'GET_VISIT_FOR_ACCOUNT_SITE_SUCCESS',
  GET_VISIT_FOR_ACCOUNT_SITE_FAILURE: 'GET_VISIT_FOR_ACCOUNT_SITE_FAILURE',

  // RESET_NOTEBOOK_DETAIL: 'RESET_NOTEBOOK_DETAIL',

  CREATE_NOTEBOOK_REQUEST: 'CREATE_NOTEBOOK_REQUEST',
  CREATE_NOTEBOOK_SUCCESS: 'CREATE_NOTEBOOK_SUCCESS',
  CREATE_NOTEBOOK_FAILURE: 'CREATE_NOTEBOOK_FAILURE',
  RESET_CREATE_NOTEBOOK_REQUEST: 'RESET_CREATE_NOTEBOOK_REQUEST',

  VISIT_GET_BY_SITE_NAME_REQUEST: 'VISIT_GET_BY_SITE_NAME_REQUEST',
  VISIT_GET_BY_SITE_NAME_SUCCESS: 'VISIT_GET_BY_SITE_NAME_SUCCESS',
  VISIT_GET_BY_SITE_NAME_FAILURE: 'VISIT_GET_BY_SITE_NAME_FAILURE',

  REMOVE_NOTE_BOOK_TRAIL: 'REMOVE_NOTE_BOOK_TRAIL',

  GET_NOTEBOOK_BY_ID_REQUEST: 'GET_NOTEBOOK_BY_ID_REQUEST',
  GET_NOTEBOOK_BY_ID_SUCCESS: 'GET_NOTEBOOK_BY_ID_SUCCESS',
  GET_NOTEBOOK_BY_ID_FAILURE: 'GET_NOTEBOOK_BY_ID_FAILURE',

  UPDATE_NOTEBOOK_REQUEST: 'UPDATE_NOTEBOOK_REQUEST',
  UPDATE_NOTEBOOK_SUCCESS: 'UPDATE_NOTEBOOK_SUCCESS',
  UPDATE_NOTEBOOK_FAILURE: 'UPDATE_NOTEBOOK_FAILURE',

  UPDATE_FAVORITE_NOTEBOOK_REQUEST: 'UPDATE_FAVORITE_NOTEBOOK_REQUEST',
  UPDATE_FAVORITE_NOTEBOOK_SUCCESS: 'UPDATE_FAVORITE_NOTEBOOK_SUCCESS',
  UPDATE_FAVORITE_NOTEBOOK_FAILURE: 'UPDATE_FAVORITE_NOTEBOOK_FAILURE',

  PUSH_ADDED_NOTEBOOK_REQUEST: 'PUSH_ADDED_NOTEBOOK_REQUEST',
  PUSH_ADDED_NOTEBOOK_SUCCESS: 'PUSH_ADDED_NOTEBOOK_SUCCESS',
  PUSH_ADDED_NOTEBOOK_FAILURE: 'PUSH_ADDED_NOTEBOOK_FAILURE',

  PUSH_UPDATE_NOTEBOOK_REQUEST: 'PUSH_UPDATE_NOTEBOOK_REQUEST',
  PUSH_UPDATE_NOTEBOOK_SUCCESS: 'PUSH_UPDATE_NOTEBOOK_SUCCESS',
  PUSH_UPDATE_NOTEBOOK_FAILURE: 'PUSH_UPDATE_NOTEBOOK_FAILURE',

  SHARE_NOTEBOOK_REQUEST: 'SHARE_NOTEBOOK_REQUEST',
  SHARE_NOTEBOOK_SUCCESS: 'SHARE_NOTEBOOK_SUCCESS',
  SHARE_NOTEBOOK_FAILURE: 'SHARE_NOTEBOOK_FAILURE',

  UPLOAD_NOTEBOOK_MEDIA_REQUEST: 'UPLOAD_NOTEBOOK_MEDIA_REQUEST',
  UPLOAD_NOTEBOOK_MEDIA_SUCCESS: 'UPLOAD_NOTEBOOK_MEDIA_SUCCESS',
  UPLOAD_NOTEBOOK_MEDIA_FAILURE: 'UPLOAD_NOTEBOOK_MEDIA_FAILURE',

  DOWNLOAD_NOTEBOOK_MEDIA_REQUEST: 'DOWNLOAD_NOTEBOOK_MEDIA_REQUEST',
  DOWNLOAD_NOTEBOOK_MEDIA_SUCCESS: 'DOWNLOAD_NOTEBOOK_MEDIA_SUCCESS',
  DOWNLOAD_NOTEBOOK_MEDIA_FAILURE: 'DOWNLOAD_NOTEBOOK_MEDIA_FAILURE',

  DELETE_NOTE_LOADING: 'DELETE_NOTE_LOADING',

  GET_FILTERED_NOTES_SUCCESS: 'GET_FILTERED_NOTES_SUCCESS',

  CONFIRM_DELETE_NOTE_REQUEST: 'CONFIRM_DELETE_NOTE_REQUEST',
  CONFIRM_DELETE_NOTE_SUCCESS: 'CONFIRM_DELETE_NOTE_SUCCESS',
  CONFIRM_DELETE_NOTE_FAILURE: 'CONFIRM_DELETE_NOTE_FAILURE',

  NEW_NOTEBOOK_EDITOR: 'NEW_NOTEBOOK_EDITOR',

  CHANGE_NOTEBOOK_CATEGORY: 'CHANGE_NOTEBOOK_CATEGORY',

  UPDATE_REMINDER_TIME: 'UPDATE_REMINDER_TIME',

  SHARE_NOTEBOOK_EMAIL_REQUEST: 'SHARE_NOTEBOOK_EMAIL_REQUEST',
  SHARE_NOTEBOOK_EMAIL_SUCCESS: 'SHARE_NOTEBOOK_EMAIL_SUCCESS',
  SHARE_NOTEBOOK_EMAIL_FAILURE: 'SHARE_NOTEBOOK_EMAIL_FAILURE',

  TAKE_NOTEBOOK_PICTURE: 'TAKE_NOTEBOOK_PICTURE',

  ADD_CAMERA_IMAGE: 'ADD_CAMERA_IMAGE',

  ADD_IMAGES_ATTACHMENT: 'ADD_IMAGES_ATTACHMENT',

  ADD_VIDEOS_ATTACHMENT: 'ADD_VIDEOS_ATTACHMENT',

  SAVE_NOTEBOOK_SIGNATURE: 'SAVE_NOTEBOOK_SIGNATURE',

  ADD_IMAGES_FROM_GALLERY: 'ADD_IMAGES_FROM_GALLERY',

  ADD_GALLERY_VIDEOS: 'ADD_GALLERY_VIDEOS',

  NOTEBOOK_START_RECORDING: 'NOTEBOOK_START_RECORDING',

  NOTEBOOK_STOP_RECORDING: 'NOTEBOOK_STOP_RECORDING',

  UPDATE_AUDIO_RECORDING: 'UPDATE_AUDIO_RECORDING',

  ADD_NEW_AUDIO_RECORDING: 'ADD_NEW_AUDIO_RECORDING',

  UPDATE_RECORD_TIMER: 'UPDATE_RECORD_TIMER',

  PLAY_NOTEBOOK_AUDIO: 'PLAY_NOTEBOOK_AUDIO',

  UPDATE_PLAYING_AUDIO_LIST: 'UPDATE_PLAYING_AUDIO_LIST',

  PAUSE_NOTEBOOK_AUDIO: 'PAUSE_NOTEBOOK_AUDIO',

  DELETE_RECORDING: 'DELETE_RECORDING',

  DELETE_NOTE_MEDIA: 'DELETE_NOTE_MEDIA',

  UPDATE_NOTE_MEDIA_IMAGES: 'UPDATE_NOTE_MEDIA_IMAGES',

  UPDATE_NOTE_MEDIA_VIDEOS: 'UPDATE_NOTE_MEDIA_VIDEOS',

  UPDATE_NOTEBOOK_TITLE: 'UPDATE_NOTEBOOK_TITLE',

  UPDATE_NOTEBOOK_NOTE_HTML: 'UPDATE_NOTEBOOK_NOTE_HTML',

  SAVE_NEW_NOTEBOOK_REQUEST: 'SAVE_NEW_NOTEBOOK_REQUEST',

  UPDATE_EXISTING_NOTEBOOK_REQUEST: 'UPDATE_EXISTING_NOTEBOOK_REQUEST',

  CLEAR_NOTEBOOK_REDUCER: 'CLEAR_NOTEBOOK_REDUCER',

  UPDATE_NOTEBOOK_TRAIL: 'UPDATE_NOTEBOOK_TRAIL',

  CLEAR_NOTEBOOK_TRAIL: 'CLEAR_NOTEBOOK_TRAIL',

  CLEAR_TRAIL_NOTEBOOK_DATA: 'CLEAR_TRAIL_NOTEBOOK_DATA',

  ADD_NEW_NOTEBOOK_TRAIL_REQUEST: 'ADD_NEW_NOTEBOOK_TRAIL_REQUEST',
  ADD_NEW_NOTEBOOK_TRAIL_SUCCESS: 'ADD_NEW_NOTEBOOK_TRAIL_SUCCESS',
  ADD_NEW_NOTEBOOK_TRAIL_FAILURE: 'ADD_NEW_NOTEBOOK_TRAIL_FAILURE',

  EDIT_NOTEBOOK_TRAIL: 'EDIT_NOTEBOOK_TRAIL',

  GET_NOTEBOOK_MEDIA_ITEMS: 'GET_NOTEBOOK_MEDIA_ITEMS',

  GET_UNIQUE_CREATOR_LIST_FOR_NOTEBOOK_REQUEST:
    'GET_UNIQUE_CREATOR_LIST_FOR_NOTEBOOK_REQUEST',
  GET_UNIQUE_CREATOR_LIST_FOR_NOTEBOOK_SUCCESS:
    'GET_UNIQUE_CREATOR_LIST_FOR_NOTEBOOK_SUCCESS',
  GET_UNIQUE_CREATOR_LIST_FOR_NOTEBOOK_FAILURE:
    'GET_UNIQUE_CREATOR_LIST_FOR_NOTEBOOK_FAILURE',

  REQUEST_NOTEBOOK_MEDIA_LOADER: 'REQUEST_NOTEBOOK_MEDIA_LOADER',

  CLEAR_NOTEBOOK_EDITOR_REQUEST: 'CLEAR_NOTEBOOK_EDITOR_REQUEST',
};
