export default {
  SYNC_NOTIFICATIONS_REQUEST: 'SYNC_NOTIFICATIONS_REQUEST',
  SYNC_NOTIFICATIONS_SUCCESS: 'SYNC_NOTIFICATIONS_SUCCESS',
  SYNC_NOTIFICATIONS_FAILURE: 'SYNC_NOTIFICATIONS_FAILURE',

  TWENTY_FOUR_HOURS_AND_NO_SYNC_REQUEST:
    'TWENTY_FOUR_HOURS_AND_NO_SYNC_REQUEST',
  TWENTY_FOUR_HOURS_AND_NO_SYNC_SUCCESS:
    'TWENTY_FOUR_HOURS_AND_NO_SYNC_SUCCESS',
  TWENTY_FOUR_HOURS_AND_NO_SYNC_FAILURE:
    'TWENTY_FOUR_HOURS_AND_NO_SYNC_FAILURE',

  GET_NOTIFICATIONS_REQUEST: 'GET_NOTIFICATIONS_REQUEST',
  GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
  GET_NOTIFICATIONS_FAILURE: 'GET_NOTIFICATIONS_FAILURE',

  GET_NOTIFICATIONS_COUNT_REQUEST: 'GET_NOTIFICATIONS_COUNT_REQUEST',
  GET_NOTIFICATIONS_COUNT_SUCCESS: 'GET_NOTIFICATIONS_COUNT_SUCCESS',
  GET_NOTIFICATIONS_COUNT_FAILURE: 'GET_NOTIFICATIONS_COUNT_FAILURE',

  MARK_NOTIFICATION_READ_REQUEST: 'MARK_NOTIFICATION_READ_REQUEST',
  MARK_NOTIFICATION_READ_SUCCESS: 'MARK_NOTIFICATION_READ_SUCCESS',
  MARK_NOTIFICATION_READ_FAILURE: 'MARK_NOTIFICATION_READ_FAILURE',

  MARK_ALL_NOTIFICATION_READ_REQUEST: 'MARK_ALL_NOTIFICATION_READ_REQUEST',
  MARK_ALL_NOTIFICATION_READ_SUCCESS: 'MARK_ALL_NOTIFICATION_READ_SUCCESS',
  MARK_ALL_NOTIFICATION_READ_FAILURE: 'MARK_ALL_NOTIFICATION_READ_FAILURE',
  RESET_MARK_ALL_NOTIFICATION_READ_REQUEST:
    'RESET_MARK_ALL_NOTIFICATION_READ_REQUEST',

  MARK_NOTIFICATION_AS_READ_REQUEST: 'MARK_NOTIFICATION_AS_READ_REQUEST',
  MARK_NOTIFICATION_AS_READ_SUCCESS: 'MARK_NOTIFICATION_AS_READ_SUCCESS',

  ONE_DAY_AND_NO_SYNC_REQUEST: 'ONE_DAY_AND_NO_SYNC_REQUEST',

  DOWNLOAD_NOTIFICATION_MEDIA_REQUEST: 'DOWNLOAD_NOTIFICATION_MEDIA_REQUEST',
  DOWNLOAD_NOTIFICATION_MEDIA_SUCCESS: 'DOWNLOAD_NOTIFICATION_MEDIA_SUCCESS',
  DOWNLOAD_NOTIFICATION_MEDIA_FAILURE: 'DOWNLOAD_NOTIFICATION_MEDIA_FAILURE',

  START_DASHBOARD_NOTIFICATIONS_SYNCING:
    'START_DASHBOARD_NOTIFICATIONS_SYNCING',
  END_DASHBOARD_NOTIFICATIONS_SYNCING: 'END_DASHBOARD_NOTIFICATIONS_SYNCING',
};
