export default {
  SYNC_PENS_REQUEST: 'SYNC_PENS_REQUEST',
  SYNC_PENS_SUCCESS: 'SYNC_PENS_SUCCESS',
  SYNC_PENS_FAILURE: 'SYNC_PENS_FAILURE',

  GET_PENS_REQUEST: 'GET_PENS_REQUEST',
  GET_PENS_SUCCESS: 'GET_PENS_SUCCESS',
  GET_PENS_FAILURE: 'GET_PENS_FAILURE',

  CREATE_PEN_REQUEST: 'CREATE_PEN_REQUEST',
  CREATE_PEN_SUCCESS: 'CREATE_PEN_SUCCESS',
  CREATE_PEN_FAILURE: 'CREATE_PEN_FAILURE',

  GET_PEN_BY_ID_REQUEST: 'GET_PEN_BY_ID_REQUEST',
  GET_PEN_BY_ID_SUCCESS: 'GET_PEN_BY_ID_SUCCESS',
  GET_PEN_BY_ID_FAILURE: 'GET_PEN_BY_ID_FAILURE',

  UPDATE_PEN_REQUEST: 'UPDATE_PEN_REQUEST',
  UPDATE_PEN_SUCCESS: 'UPDATE_PEN_SUCCESS',
  UPDATE_PEN_FAILURE: 'UPDATE_PEN_FAILURE',

  PUSH_ADDED_PENS_REQUEST: 'PUSH_ADDED_PENS_REQUEST',
  PUSH_ADDED_PENS_SUCCESS: 'PUSH_ADDED_PENS_SUCCESS',
  PUSH_ADDED_PENS_FAILURE: 'PUSH_ADDED_PENS_FAILURE',

  PUSH_UPDATED_PENS_REQUEST: 'PUSH_UPDATED_PENS_REQUEST',
  PUSH_UPDATED_PENS_SUCCESS: 'PUSH_UPDATED_PENS_SUCCESS',
  PUSH_UPDATED_PENS_FAILURE: 'PUSH_UPDATED_PENS_FAILURE',

  RESET_CREATE_PEN_REQUEST: 'RESET_CREATE_PEN_REQUEST',
  RESET_UPDATE_PEN_REQUEST: 'RESET_UPDATE_PEN_REQUEST',
  RESET_GET_PEN_REQUEST: 'RESET_GET_PEN_REQUEST',

  RESET_PEN_FILTERS: 'RESET_PEN_FILTERS',
  RESET_PEN_DETAIL: 'RESET_PEN_DETAIL',

  SET_ACTIVE_PEN_DELETING_ID: 'SET_ACTIVE_PEN_DELETING_ID',

  DELETE_PEN_BY_ID_REQUEST: 'DELETE_PEN_BY_ID_REQUEST',
  DELETE_PEN_BY_ID_SUCCESS: 'DELETE_PEN_BY_ID_SUCCESS',
  DELETE_PEN_BY_ID_FAILURE: 'DELETE_PEN_BY_ID_FAILURE',

  GET_PENS_BY_SITE_ID_REQUEST: 'GET_PENS_BY_SITE_ID_REQUEST',
  GET_PENS_BY_SITE_ID_SUCCESS: 'GET_PENS_BY_SITE_ID_SUCCESS',
  GET_PENS_BY_SITE_ID_FAILURE: 'GET_PENS_BY_SITE_ID_FAILURE',

  GET_IN_PROGRESS_VISITS_FOR_DELETING_PEN_REQUEST:
    'GET_IN_PROGRESS_VISITS_FOR_DELETING_PEN_REQUEST',
  GET_IN_PROGRESS_VISITS_FOR_DELETING_PEN_SUCCESS:
    'GET_IN_PROGRESS_VISITS_FOR_DELETING_PEN_SUCCESS',
  GET_IN_PROGRESS_VISITS_FOR_DELETING_PEN_FAILURE:
    'GET_IN_PROGRESS_VISITS_FOR_DELETING_PEN_FAILURE',
};
