export default {
  SYNC_PROSPECT_REQUEST: 'SYNC_PROSPECT_REQUEST',
  SYNC_PROSPECT_SUCCESS: 'SYNC_PROSPECT_SUCCESS',
  SYNC_PROSPECT_FAILURE: 'SYNC_PROSPECT_FAILURE',

  CREATE_PROSPECT_REQUEST: 'CREATE_PROSPECT_REQUEST',
  CREATE_PROSPECT_SUCCESS: 'CREATE_PROSPECT_SUCCESS',
  CREATE_PROSPECT_FAILURE: 'CREATE_PROSPECT_FAILURE',

  UPDATE_PROSPECT_REQUEST: 'UPDATE_PROSPECT_REQUEST',
  UPDATE_PROSPECT_SUCCESS: 'UPDATE_PROSPECT_SUCCESS',
  UPDATE_PROSPECT_FAILURE: 'UPDATE_PROSPECT_FAILURE',

  PUSH_ADDED_PROSPECTS_REQUEST: 'PUSH_ADDED_PROSPECTS_REQUEST',
  PUSH_ADDED_PROSPECTS_SUCCESS: 'PUSH_ADDED_PROSPECTS_SUCCESS',
  PUSH_ADDED_PROSPECTS_FAILURE: 'PUSH_ADDED_PROSPECTS_FAILURE',

  PUSH_UPDATED_PROSPECTS_REQUEST: 'PUSH_UPDATED_PROSPECTS_REQUEST',
  PUSH_UPDATED_PROSPECTS_SUCCESS: 'PUSH_UPDATED_PROSPECTS_SUCCESS',
  PUSH_UPDATED_PROSPECTS_FAILURE: 'PUSH_UPDATED_PROSPECTS_FAILURE',

  RESET_CREATE_PROSPECT_REQUEST: 'RESET_CREATE_PROSPECT_REQUEST',
  RESET_UPDATE_PROSPECT_REQUEST: 'RESET_UPDATE_PROSPECT_REQUEST',

  GET_PROSPECT_BY_LOCAL_OR_SERVER_ID_REQUEST:
    'GET_PROSPECT_BY_LOCAL_OR_SERVER_ID_REQUEST',
  GET_PROSPECT_BY_LOCAL_OR_SERVER_ID_SUCCESS:
    'GET_PROSPECT_BY_LOCAL_OR_SERVER_ID_SUCCESS',
  GET_PROSPECT_BY_LOCAL_OR_SERVER_ID_FAILURE:
    'GET_PROSPECT_BY_LOCAL_OR_SERVER_ID_FAILURE',

  GET_PROSPECT_BY_ID_REQUEST: 'GET_PROSPECT_BY_ID_REQUEST',
  GET_PROSPECT_BY_ID_SUCCESS: 'GET_PROSPECT_BY_ID_SUCCESS',
  GET_PROSPECT_BY_ID_FAILURE: 'GET_PROSPECT_BY_ID_FAILURE',
};
