export default {
  INITIALIZE_ROBOTIC_MILK: 'INITIALIZE_ROBOTIC_MILK',

  CHANGE_ROBOT_TYPE: 'CHANGE_ROBOT_TYPE',
  CHANGE_COW_FLOW_DESIGN: 'CHANGE_COW_FLOW_DESIGN',
  UPDATE_FORM_FIELD: 'UPDATE_FORM_FIELD',

  SAVE_ROBOTIC_MILK_DATA_TO_DB: 'SAVE_ROBOTIC_MILK_DATA_TO_DB',

  CLEAR_ROBOTIC_MILK_DATA: 'CLEAR_ROBOTIC_MILK_DATA',

  SET_VISIT_ROBOTIC_MILK_STATE: 'SET_VISIT_ROBOTIC_MILK_STATE',

  CHANGE_RESULTS_TAB: 'CHANGE_RESULTS_TAB',

  UPDATE_ROBOTIC_MILK_VISITS_OF_SITE: 'UPDATE_ROBOTIC_MILK_VISITS_OF_SITE',
};
