export default {
  FETCH_MEDIA_FROM_S3_REQUEST: 'FETCH_MEDIA_FROM_S3_REQUEST',
  FETCH_MEDIA_FROM_S3_SUCCESS: 'FETCH_MEDIA_FROM_S3_SUCCESS',
  FETCH_MEDIA_FROM_S3_FAILURE: 'FETCH_MEDIA_FROM_S3_FAILURE',

  UPLOAD_MEDIA_TO_S3_REQUEST: 'UPLOAD_MEDIA_TO_S3_REQUEST',
  UPLOAD_MEDIA_TO_S3_SUCCESS: 'UPLOAD_MEDIA_TO_S3_SUCCESS',
  UPLOAD_MEDIA_TO_S3_FAILURE: 'UPLOAD_MEDIA_TO_S3_FAILURE',

  UPLOAD_NOTEBOOK_MEDIA_TO_S3_REQUEST: 'UPLOAD_NOTEBOOK_MEDIA_TO_S3_REQUEST',
  UPLOAD_NOTEBOOK_MEDIA_TO_S3_SUCCESS: 'UPLOAD_NOTEBOOK_MEDIA_TO_S3_SUCCESS',
  UPLOAD_NOTEBOOK_MEDIA_TO_S3_FAILURE: 'UPLOAD_NOTEBOOK_MEDIA_TO_S3_FAILURE',

  FETCH_NOTEBOOK_MEDIA_TO_S3_REQUEST: 'FETCH_NOTEBOOK_MEDIA_TO_S3_REQUEST',
  FETCH_NOTEBOOK_MEDIA_TO_S3_SUCCESS: 'FETCH_NOTEBOOK_MEDIA_TO_S3_SUCCESS',
  FETCH_NOTEBOOK_MEDIA_TO_S3_FAILURE: 'FETCH_NOTEBOOK_MEDIA_TO_S3_FAILURE',

  GET_NOTEBOOK_MEDIA_BY_ID_REQUEST: 'GET_NOTEBOOK_MEDIA_BY_ID_REQUEST',
  GET_NOTEBOOK_MEDIA_BY_ID_SUCCESS: 'GET_NOTEBOOK_MEDIA_BY_ID_SUCCESS',
  GET_NOTEBOOK_MEDIA_BY_ID_FAILURE: 'GET_NOTEBOOK_MEDIA_BY_ID_FAILURE',

  DELETE_NOTEBOOK_MEDIA_BY_ID_REQUEST: 'DELETE_NOTEBOOK_MEDIA_BY_ID_REQUEST',

  DOWNLOAD_SPECIFIC_NOTEBOOK_MEDIA_REQUEST:
    'DOWNLOAD_SPECIFIC_NOTEBOOK_MEDIA_REQUEST',
  DOWNLOAD_SPECIFIC_NOTEBOOK_MEDIA_SUCCESS:
    'DOWNLOAD_SPECIFIC_NOTEBOOK_MEDIA_SUCCESS',
  DOWNLOAD_SPECIFIC_NOTEBOOK_MEDIA_FAILURE:
    'DOWNLOAD_SPECIFIC_NOTEBOOK_MEDIA_FAILURE',

  // RESET_NOTEBOOK_MEDIA_REQUEST: 'RESET_NOTEBOOK_MEDIA_REQUEST',

  DELETE_ALL_MEDIA_ITEMS_BY_NOTEBOOK: 'DELETE_ALL_MEDIA_ITEMS_BY_NOTEBOOK',
};
