export default {
  GET_SEGMENTS_REQUEST: 'GET_SEGMENTS_REQUEST',
  GET_SEGMENTS_SUCCESS: 'GET_SEGMENTS_SUCCESS',
  GET_SEGMENTS_FAILURE: 'GET_SEGMENTS_FAILURE',

  SYNC_SEGMENTS_REQUEST: 'SYNC_SEGMENTS_REQUEST',
  SYNC_SEGMENTS_SUCCESS: 'SYNC_SEGMENTS_SUCCESS',
  SYNC_SEGMENTS_FAILURE: 'SYNC_SEGMENTS_FAILURE',
};
