export default {
  CREATE_SILAGE_REQUEST: 'CREATE_SILAGE_REQUEST',
  CREATE_SILAGE_SUCCESS: 'CREATE_SILAGE_SUCCESS',
  CREATE_SILAGE_FAILURE: 'CREATE_SILAGE_FAILURE',
  RESET_CREATE_SILAGE_REQUEST: 'RESET_CREATE_SILAGE_REQUEST',

  UPDATE_SILAGE_REQUEST: 'UPDATE_SILAGE_REQUEST',
  UPDATE_SILAGE_SUCCESS: 'UPDATE_SILAGE_SUCCESS',
  UPDATE_SILAGE_FAILURE: 'UPDATE_SILAGE_FAILURE',
  RESET_UPDATE_SILAGE_REQUEST: 'RESET_UPDATE_SILAGE_REQUEST',

  GET_ALL_SILAGES_REQUEST: 'GET_ALL_SILAGES_REQUEST',
  GET_ALL_SILAGES_SUCCESS: 'GET_ALL_SILAGES_SUCCESS',
  GET_ALL_SILAGES_FAILURE: 'GET_ALL_SILAGES_FAILURE',

  GET_UPDATED_SILAGES_REQUEST: 'GET_UPDATED_SILAGES_REQUEST',
  GET_UPDATED_SILAGES_SUCCESS: 'GET_UPDATED_SILAGES_SUCCESS',
  GET_UPDATED_SILAGES_FAILURE: 'GET_UPDATED_SILAGES_FAILURE',

  SYNC_SILAGES_REQUEST: 'SYNC_SILAGES_REQUEST',
  SYNC_SILAGES_SUCCESS: 'SYNC_SILAGES_SUCCESS',
  SYNC_SILAGES_FAILURE: 'SYNC_SILAGES_FAILURE',

};
