export default {
  SYNC_SITES_REQUEST: 'SYNC_SITES_REQUEST',
  SYNC_SITES_SUCCESS: 'SYNC_SITES_SUCCESS',
  SYNC_SITES_FAILURE: 'SYNC_SITES_FAILURE',

  GET_SITES_REQUEST: 'GET_SITES_REQUEST',
  GET_SITES_SUCCESS: 'GET_SITES_SUCCESS',
  GET_SITES_FAILURE: 'GET_SITES_FAILURE',

  CREATE_SITE_REQUEST: 'CREATE_SITE_REQUEST',
  CREATE_SITE_SUCCESS: 'CREATE_SITE_SUCCESS',
  CREATE_SITE_FAILURE: 'CREATE_SITE_FAILURE',

  CREATE_PENS_IN_SITE_REQUEST: 'CREATE_PENS_IN_SITE_REQUEST',
  UPDATE_PENS_IN_SITE_REQUEST: 'UPDATE_PENS_IN_SITE_REQUEST',
  CREATE_PENS_IN_SITE_DB_REQUEST: 'CREATE_PENS_IN_SITE_DB_REQUEST',
  CREATE_PENS_IN_SITE_DB_SUCCESS: 'CREATE_PENS_IN_SITE_DB_SUCCESS',
  CREATE_PENS_IN_SITE_DB_FAILURE: 'CREATE_PENS_IN_SITE_DB_FAILURE',

  GET_SITE_BY_ID_REQUEST: 'GET_SITE_BY_ID_REQUEST',
  GET_SITE_BY_ID_SUCCESS: 'GET_SITE_BY_ID_SUCCESS',
  GET_SITE_BY_ID_FAILURE: 'GET_SITE_BY_ID_FAILURE',

  UPDATE_SITE_REQUEST: 'UPDATE_SITE_REQUEST',
  UPDATE_SITE_SUCCESS: 'UPDATE_SITE_SUCCESS',
  UPDATE_SITE_FAILURE: 'UPDATE_SITE_FAILURE',

  PUSH_ADDED_SITES_REQUEST: 'PUSH_ADDED_SITES_REQUEST',
  PUSH_ADDED_SITES_SUCCESS: 'PUSH_ADDED_SITES_SUCCESS',
  PUSH_ADDED_SITES_FAILURE: 'PUSH_ADDED_SITES_FAILURE',

  PUSH_UPDATED_SITES_REQUEST: 'PUSH_UPDATED_SITES_REQUEST',
  PUSH_UPDATED_SITES_SUCCESS: 'PUSH_UPDATED_SITES_SUCCESS',
  PUSH_UPDATED_SITES_FAILURE: 'PUSH_UPDATED_SITES_FAILURE',

  RESET_CREATE_SITE_REQUEST: 'RESET_CREATE_SITE_REQUEST',
  RESET_UPDATE_SITE_REQUEST: 'RESET_UPDATE_SITE_REQUEST',
  RESET_GET_SITES_REQUEST: 'RESET_GET_SITES_REQUEST',

  RESET_SITE_FILTERS: 'RESET_SITE_FILTERS',
  RESET_SITE_DETAIL: 'RESET_SITE_DETAIL',

  GET_SITE_BY_VISIT_REQUEST: 'GET_SITE_BY_VISIT_REQUEST',
  GET_SITE_BY_VISIT_SUCCESS: 'GET_SITE_BY_VISIT_SUCCESS',
  GET_SITE_BY_VISIT_FAILURE: 'GET_SITE_BY_VISIT_FAILURE',

  UPDATE_TOOL_SITE_REQUEST: 'UPDATE_TOOL_SITE_REQUEST',
  UPDATE_TOOL_SITE_SUCCESS: 'UPDATE_TOOL_SITE_SUCCESS',
  UPDATE_TOOL_SITE_FAILURE: 'UPDATE_TOOL_SITE_FAILURE',
  UPDATE_BCS_SCALE_REQUEST: 'UPDATE_BCS_SCALE_REQUEST',

  RESET_SITE_REQUEST: 'RESET_SITE_REQUEST',

  DOWNLOAD_SHARE_POINT_REPORT_REQUEST: 'DOWNLOAD_SHARE_POINT_REPORT_REQUEST',
  DOWNLOAD_SHARE_POINT_REPORT_SUCCESS: 'DOWNLOAD_SHARE_POINT_REPORT_SUCCESS',
  DOWNLOAD_SHARE_POINT_REPORT_FAILURE: 'DOWNLOAD_SHARE_POINT_REPORT_FAILURE',
  RESET_DOWNLOAD_SHARE_POINT_REPORT_FLAGS:
    'RESET_DOWNLOAD_SHARE_POINT_REPORT_FLAGS',

  GET_ALL_ACCOUNT_SITES_REQUEST: 'GET_ALL_ACCOUNT_SITES_REQUEST',
  GET_ALL_ACCOUNT_SITES_SUCCESS: 'GET_ALL_ACCOUNT_SITES_SUCCESS',
  GET_ALL_ACCOUNT_SITES_FAILURE: 'GET_ALL_ACCOUNT_SITES_FAILURE',
};
