export default {
  INITIALIZE_TMR_PARTICLE_SCORE: 'INITIALIZE_TMR_PARTICLE_SCORE',

  RESTORE_TMR_PARTICLE_SCORE_DATA: 'RESTORE_TMR_PARTICLE_SCORE_DATA',

  SAVE_TMR_DATA_TO_DB: 'SAVE_TMR_DATA_TO_DB',
  
  UPDATE_TMR_GOALS_BY_SCORER: 'UPDATE_TMR_GOALS_BY_SCORER',

  CHANGE_TMR_SCORER: 'CHANGE_TMR_SCORER',
  
  SAVE_TMR_GOALS: 'SAVE_TMR_GOALS',

  ADD_NEW_SCORER: 'ADD_NEW_SCORER',
  
  UPDATE_TMR_SCORES: 'UPDATE_TMR_SCORES',

  RESTORE_PREVIOUS_TMR_GOALS: 'RESTORE_PREVIOUS_TMR_GOALS',

  CHANGE_RESULTS_TAB: 'CHANGE_RESULTS_TAB',

};
