export default {
  RESET_SAVE_ACTIVE_TOOL_REQUEST: 'RESET_SAVE_ACTIVE_TOOL_REQUEST',
  SAVE_ACTIVE_TOOL_REQUEST: 'SAVE_ACTIVE_TOOL_REQUEST',

  RESET_SAVE_ACTIVE_PEN_REQUEST: 'RESET_SAVE_ACTIVE_PEN_REQUEST',
  SAVE_ACTIVE_PEN_REQUEST: 'SAVE_ACTIVE_PEN_REQUEST',

  RESET_SAVE_ACTIVE_SCREEN_REQUEST: 'RESET_SAVE_ACTIVE_SCREEN_REQUEST',
  SAVE_ACTIVE_SCREEN_REQUEST: 'SAVE_ACTIVE_SCREEN_REQUEST',

  RESET_TOOL_SWITCH_REQUEST: 'RESET_TOOL_SWITCH_REQUEST',
};
