export default {
  SET_ACTIVE_TOOL_REQUEST: 'SET_ACTIVE_TOOL_REQUEST',

  SET_ACTIVE_CATEGORY_TOOL_REQUEST: 'SET_ACTIVE_CATEGORY_TOOL_REQUEST',

  CLEAR_ALL_TOOLS_DATA_REQUEST: 'CLEAR_ALL_TOOLS_DATA_REQUEST',

  CLEAR_CATEGORY_TOOL_REQUEST: 'CLEAR_CATEGORY_TOOL_REQUEST',

  // @TODO remove as not used
  GET_SITE_PENS_TIME_BUDGET_REQUEST: 'GET_SITE_PENS_TIME_BUDGET_REQUEST',
  GET_SITE_PENS_TIME_BUDGET_SUCCESS: 'GET_SITE_PENS_TIME_BUDGET_SUCCESS',
  GET_SITE_PENS_TIME_BUDGET_FAILURE: 'GET_SITE_PENS_TIME_BUDGET_FAILURE',
  RESET_SITE_PENS_TIME_BUDGET_REQUEST: 'RESET_SITE_PENS_TIME_BUDGET_REQUEST',

  GET_SITE_PENS_REQUEST: 'GET_SITE_PENS_REQUEST',
  GET_SITE_PENS_SUCCESS: 'GET_SITE_PENS_SUCCESS',
  GET_SITE_PENS_FAILURE: 'GET_SITE_PENS_FAILURE',

  GET_SITE_REQUEST: 'GET_SITE_REQUEST',
  GET_SITE_SUCCESS: 'GET_SITE_SUCCESS',
  GET_SITE_FAILURE: 'GET_SITE_FAILURE',

  DOWNLOAD_TOOL_EXCEL_REQUEST: 'DOWNLOAD_TOOL_EXCEL_REQUEST',
  DOWNLOAD_TOOL_EXCEL_SUCCESS: 'DOWNLOAD_TOOL_EXCEL_SUCCESS',
  DOWNLOAD_TOOL_EXCEL_FAILURE: 'DOWNLOAD_TOOL_EXCEL_FAILURE',

  DOWNLOAD_TOOL_IMAGE_REQUEST: 'DOWNLOAD_TOOL_IMAGE_REQUEST',
  DOWNLOAD_TOOL_IMAGE_SUCCESS: 'DOWNLOAD_TOOL_IMAGE_SUCCESS',
  DOWNLOAD_TOOL_IMAGE_FAILURE: 'DOWNLOAD_TOOL_IMAGE_FAILURE',

  EMAIL_TOOL_EXCEL_REQUEST: 'EMAIL_TOOL_EXCEL_REQUEST',
  EMAIL_TOOL_EXCEL_SUCCESS: 'EMAIL_TOOL_EXCEL_SUCCESS',
  EMAIL_TOOL_EXCEL_FAILURE: 'EMAIL_TOOL_EXCEL_FAILURE',

  EMAIL_TOOL_IMAGE_REQUEST: 'EMAIL_TOOL_IMAGE_REQUEST',
  EMAIL_TOOL_IMAGE_SUCCESS: 'EMAIL_TOOL_IMAGE_SUCCESS',
  EMAIL_TOOL_IMAGE_FAILURE: 'EMAIL_TOOL_IMAGE_FAILURE',

  GET_RECENT_VISITS_FOR_TOOL_REQUEST: 'GET_RECENT_VISITS_FOR_TOOL_REQUEST',
  GET_RECENT_VISITS_FOR_TOOL_SUCCESS: 'GET_RECENT_VISITS_FOR_TOOL_SUCCESS',
  GET_RECENT_VISITS_FOR_TOOL_FAILURE: 'GET_RECENT_VISITS_FOR_TOOL_FAILURE',

  UPDATE_PEN_DIM_REQUEST: 'UPDATE_PEN_DIM_REQUEST',

  RESET_DOWNLOAD_TOOL_REPORT_FLAGS: 'RESET_DOWNLOAD_TOOL_REPORT_FLAGS',

  SET_SELECTED_PEN_REQUEST: 'SET_SELECTED_PEN_REQUEST',
};
