export default {
  FAVORITIZE_TOOL_REQUEST: 'FAVORITIZE_TOOL_REQUEST',
  FAVORITIZE_TOOL_SUCCESS: 'FAVORITIZE_TOOL_SUCCESS',
  FAVORITIZE_TOOL_FAILURE: 'FAVORITIZE_TOOL_FAILURE',
  RESET_FAVORITIZE_TOOL: 'RESET_FAVORITIZE_TOOL',

  HIDE_BCS_TOAST_REQUEST: 'HIDE_BCS_TOAST_REQUEST',
  HIDE_BCS_TOAST_SUCCESS: 'HIDE_BCS_TOAST_SUCCESS',
  HIDE_BCS_TOAST_FAILURE: 'HIDE_BCS_TOAST_FAILURE',

  SYNC_USER_PREFERENCES_REQUEST: 'SYNC_USER_PREFERENCES_REQUEST',
  SYNC_USER_PREFERENCES_SUCCESS: 'SYNC_USER_PREFERENCES_SUCCESS',
  SYNC_USER_PREFERENCES_FAILURE: 'SYNC_USER_PREFERENCES_FAILURE',

  UPDATE_USER_PREFERENCE_REQUEST: 'UPDATE_USER_PREFERENCE_REQUEST',
  UPDATE_USER_PREFERENCE_SUCCESS: 'UPDATE_USER_PREFERENCE_SUCCESS',
  UPDATE_USER_PREFERENCE_FAILURE: 'UPDATE_USER_PREFERENCE_FAILURE',

  HIDE_MANURE_SCORE_TOAST_REQUEST: 'HIDE_MANURE_SCORE_TOAST_REQUEST',
  HIDE_MANURE_SCORE_TOAST_SUCCESS: 'HIDE_MANURE_SCORE_TOAST_SUCCESS',
  HIDE_MANURE_SCORE_TOAST_FAILURE: 'HIDE_MANURE_SCORE_TOAST_FAILURE',

  HIDE_CUD_CHEWING_TOAST_REQUEST: 'HIDE_CUD_CHEWING_TOAST_REQUEST',
  HIDE_CUD_CHEWING_TOAST_SUCCESS: 'HIDE_CUD_CHEWING_TOAST_SUCCESS',
  HIDE_CUD_CHEWING_TOAST_FAILURE: 'HIDE_CUD_CHEWING_TOAST_FAILURE',

  HIDE_LOCOMOTION_SCORE_TOAST_REQUEST: 'HIDE_LOCOMOTION_SCORE_TOAST_REQUEST',
  HIDE_LOCOMOTION_SCORE_TOAST_SUCCESS: 'HIDE_LOCOMOTION_SCORE_TOAST_SUCCESS',
  HIDE_LOCOMOTION_SCORE_TOAST_FAILURE: 'HIDE_LOCOMOTION_SCORE_TOAST_FAILURE',

  HIDE_MILK_SOLID_TOAST_REQUEST: 'HIDE_MILK_SOLID_TOAST_REQUEST',
  HIDE_MILK_SOLID_TOAST_SUCCESS: 'HIDE_MILK_SOLID_TOAST_SUCCESS',
  HIDE_MILK_SOLID_TOAST_FAILURE: 'HIDE_MILK_SOLID_TOAST_FAILURE',

  HIDE_ROBOTIC_MILKING_TOAST_REQUEST: 'HIDE_ROBOTIC_MILKING_TOAST_REQUEST',
  HIDE_ROBOTIC_MILKING_TOAST_SUCCESS: 'HIDE_ROBOTIC_MILKING_TOAST_SUCCESS',
  HIDE_ROBOTIC_MILKING_TOAST_FAILURE: 'HIDE_ROBOTIC_MILKING_TOAST_FAILURE',

  HIDE_METABOLIC_INCIDENCE_TOAST_REQUEST:
    'HIDE_METABOLIC_INCIDENCE_TOAST_REQUEST',
  HIDE_METABOLIC_INCIDENCE_TOAST_SUCCESS:
    'HIDE_METABOLIC_INCIDENCE_TOAST_SUCCESS',
  HIDE_METABOLIC_INCIDENCE_TOAST_FAILURE:
    'HIDE_METABOLIC_INCIDENCE_TOAST_FAILURE',

  HIDE_FORAGE_PENN_TOAST_REQUEST: 'HIDE_FORAGE_PENN_TOAST_REQUEST',
  HIDE_FORAGE_PENN_TOAST_SUCCESS: 'HIDE_FORAGE_PENN_TOAST_SUCCESS',
  HIDE_FORAGE_PENN_TOAST_FAILURE: 'HIDE_FORAGE_PENN_TOAST_FAILURE',

  HIDE_TMR_PARTICLE_SCORE_TOAST_REQUEST:
    'HIDE_TMR_PARTICLE_SCORE_TOAST_REQUEST',
  HIDE_TMR_PARTICLE_SCORE_TOAST_SUCCESS:
    'HIDE_TMR_PARTICLE_SCORE_TOAST_SUCCESS',
  HIDE_TMR_PARTICLE_SCORE_TOAST_FAILURE:
    'HIDE_TMR_PARTICLE_SCORE_TOAST_FAILURE',

  HIDE_RUMEN_FILL_TOAST_REQUEST: 'HIDE_RUMEN_FILL_TOAST_REQUEST',
  HIDE_RUMEN_FILL_TOAST_SUCCESS: 'HIDE_RUMEN_FILL_TOAST_SUCCESS',
  HIDE_RUMEN_FILL_TOAST_FAILURE: 'HIDE_RUMEN_FILL_TOAST_FAILURE',

  HIDE_PEN_TIME_BUDGET_TOAST_REQUEST: 'HIDE_PEN_TIME_BUDGET_REQUEST',
  HIDE_PEN_TIME_BUDGET_TOAST_SUCCESS: 'HIDE_PEN_TIME_BUDGET_SUCCESS',
  HIDE_PEN_TIME_BUDGET_TOAST_FAILURE: 'HIDE_PEN_TIME_BUDGET_FAILURE',

  HIDE_HEAT_STRESS_TOAST_REQUEST: 'HIDE_HEAT_STRESS_TOAST_REQUEST',
  HIDE_HEAT_STRESS_TOAST_SUCCESS: 'HIDE_HEAT_STRESS_TOAST_SUCCESS',
  HIDE_HEAT_STRESS_TOAST_FAILURE: 'HIDE_HEAT_STRESS_TOAST_FAILURE',

  UPDATE_ACCOUNT_FAVOURITE_REQUEST: 'UPDATE_ACCOUNT_FAVOURITE_REQUEST',
  UPDATE_ACCOUNT_FAVOURITE_SUCCESS: 'UPDATE_ACCOUNT_FAVOURITE_SUCCESS',
  UPDATE_ACCOUNT_FAVOURITE_FAILURE: 'UPDATE_ACCOUNT_FAVOURITE_FAILURE',

  SYNC_FETCH_USER_PREFERENCES_REQUEST: 'SYNC_FETCH_USER_PREFERENCES_REQUEST',
  SYNC_FETCH_USER_PREFERENCES_SUCCESS: 'SYNC_FETCH_USER_PREFERENCES_SUCCESS',
  SYNC_FETCH_USER_PREFERENCES_FAILURE: 'SYNC_FETCH_USER_PREFERENCES_FAILURE',

  SET_DEFAULT_CALF_HEIFER_GROWTH_SCALE_REQUEST:
    'SET_DEFAULT_CALF_HEIFER_GROWTH_SCALE_REQUEST',
  SET_DEFAULT_CALF_HEIFER_GROWTH_SCALE_SUCCESS:
    'SET_DEFAULT_CALF_HEIFER_GROWTH_SCALE_SUCCESS',
  SET_DEFAULT_CALF_HEIFER_GROWTH_SCALE_FAILURE:
    'SET_DEFAULT_CALF_HEIFER_GROWTH_SCALE_FAILURE',
};
