export default {
  SYNC_LATEST_VERSION_CONFIG_REQUESTED: 'SYNC_LATEST_VERSION_CONFIG_REQUESTED',
  SYNC_LATEST_VERSION_CONFIG_SUCCESS: 'SYNC_LATEST_VERSION_CONFIG_SUCCESS',
  SYNC_LATEST_VERSION_CONFIG_FAILURE: 'SET_IOS_ANDROID_FORCE_UPDATE_FAILURE',

  UPDATE_AVAILABLE_SUCCESS: 'UPDATE_AVAILABLE_SUCCESS',
  UPDATE_AVAILABLE_FAILURE: 'UPDATE_AVAILABLE_FAILURE',
};
