export default {
  GET_CUSTOMERS_PROSPECTS_REQUEST: 'GET_CUSTOMERS_PROSPECTS_REQUEST',
  GET_CUSTOMERS_PROSPECTS_SUCCESS: 'GET_CUSTOMERS_PROSPECTS_SUCCESS',
  GET_CUSTOMERS_PROSPECTS_FAILURE: 'GET_CUSTOMERS_PROSPECTS_FAILURE',

  GET_ACCOUNT_SITES_REQUEST: 'GET_ACCOUNT_SITES_REQUEST',
  GET_ACCOUNT_SITES_SUCCESS: 'GET_ACCOUNT_SITES_SUCCESS',
  GET_ACCOUNT_SITES_FAILURE: 'GET_ACCOUNT_SITES_FAILURE',

  GET_SITES_FOR_MULTIPLE_ACCOUNT_REQUEST:
    'GET_SITES_FOR_MULTIPLE_ACCOUNT_REQUEST',

  RESET_VISIT_DATA_REQUEST: 'RESET_VISIT_DATA_REQUEST',

  SYNC_VISITS_REQUEST: 'SYNC_VISITS_REQUEST',
  SYNC_VISITS_SUCCESS: 'SYNC_VISITS_SUCCESS',
  SYNC_VISITS_FAILURE: 'SYNC_VISITS_FAILURE',

  CREATE_VISIT_REQUEST: 'CREATE_VISIT_REQUEST',
  CREATE_VISIT_SUCCESS: 'CREATE_VISIT_SUCCESS',
  CREATE_VISIT_FAILURE: 'CREATE_VISIT_FAILURE',

  GET_RECENT_VISIT_BY_ACCOUNT_REQUEST: 'GET_RECENT_VISIT_BY_ACCOUNT_REQUEST',
  GET_RECENT_VISIT_BY_ACCOUNT_SUCCESS: 'GET_RECENT_VISIT_BY_ACCOUNT_SUCCESS',
  GET_RECENT_VISIT_BY_ACCOUNT_FAILURE: 'GET_RECENT_VISIT_BY_ACCOUNT_FAILURE',

  GET_RECENT_VISIT_BY_SITE_REQUEST: 'GET_RECENT_VISIT_BY_SITE_REQUEST',
  GET_RECENT_VISIT_BY_SITE_SUCCESS: 'GET_RECENT_VISIT_BY_SITE_SUCCESS',
  GET_RECENT_VISIT_BY_SITE_FAILURE: 'GET_RECENT_VISIT_BY_SITE_FAILURE',

  GET_ALL_RECENT_VISIT_REQUEST: 'GET_ALL_RECENT_VISIT_REQUEST',
  GET_ALL_RECENT_VISIT_SUCCESS: 'GET_ALL_RECENT_VISIT_SUCCESS',
  GET_ALL_RECENT_VISIT_FAILURE: 'GET_ALL_RECENT_VISIT_FAILURE',

  RESET_CREATE_VISIT_REQUEST: 'RESET_CREATE_VISIT_REQUEST',

  RESET_RECENT_VISIT_BY_ACCOUNT: 'RESET_RECENT_VISIT_BY_ACCOUNT',

  VISIT_RESET_FILTER: 'VISIT_RESET_FILTER',

  GET_SELECTED_VISIT_REQUEST: 'GET_SELECTED_VISIT_REQUEST',
  GET_SELECTED_VISIT_SUCCESS: 'GET_SELECTED_VISIT_SUCCESS',
  GET_SELECTED_VISIT_FAILURE: 'GET_SELECTED_VISIT_FAILURE',

  GET_SELECTED_VISIT_DASHBOARD_REQUEST: 'GET_SELECTED_VISIT_DASHBOARD_REQUEST',
  GET_SELECTED_VISIT_DASHBOARD_SUCCESS: 'GET_SELECTED_VISIT_DASHBOARD_SUCCESS',
  GET_SELECTED_VISIT_DASHBOARD_FAILURE: 'GET_SELECTED_VISIT_DASHBOARD_FAILURE',

  DELETE_VISIT_REQUEST: 'DELETE_VISIT_REQUEST',
  DELETE_VISIT_FAILURE: 'DELETE_VISIT_FAILURE',

  PUBLISH_VISIT_REQUEST: 'PUBLISH_VISIT_REQUEST',

  GET_VISIT_EXISTS_REQUEST: 'GET_VISIT_EXISTS_REQUEST',
  GET_VISIT_EXISTS_SUCCESS: 'GET_VISIT_EXISTS_SUCCESS',
  GET_VISIT_EXISTS_FAILURE: 'GET_VISIT_EXISTS_FAILURE',

  GET_ONLINE_SELECTED_VISIT_REQUEST: 'GET_ONLINE_SELECTED_VISIT_REQUEST',

  AUTO_PUBLISH_VISIT_REQUEST: 'AUTO_PUBLISH_VISIT_REQUEST',

  RESET_VISIT_HISTORY: 'RESET_VISIT_HISTORY',

  UPDATE_VISIT_UPDATE_STATUS: 'UPDATE_VISIT_UPDATE_STATUS',

  UPDATE_VISIT_TOOL_IN_PROGRESS_STATUS: 'UPDATE_VISIT_TOOL_IN_PROGRESS_STATUS',

  RESET_SITES_LIST_REQUEST: 'UPDATE_VISIT_UPDATE_STATUS',

  DELETE_VISITS_OLDER_THAN_COUNT_REQUEST:
    'DELETE_VISITS_OLDER_THAN_COUNT_REQUEST',
  DELETE_VISITS_OLDER_THAN_COUNT_SUCCESS:
    'DELETE_VISITS_OLDER_THAN_COUNT_SUCCESS',
  DELETE_VISITS_OLDER_THAN_COUNT_FAILURE:
    'DELETE_VISITS_OLDER_THAN_COUNT_FAILURE',

  PUSH_UPDATED_VISITS_REQUESTED: 'PUSH_UPDATED_VISITS_REQUESTED',
  PUSH_UPDATED_VISITS_SUCCESS: 'PUSH_UPDATED_VISITS_SUCCESS',
  PUSH_UPDATED_VISITS_FAILURE: 'PUSH_UPDATED_VISITS_FAILURE',

  PUSH_ADDED_VISITS_REQUESTED: 'PUSH_ADDED_VISITS_REQUESTED',
  PUSH_ADDED_VISITS_SUCCESS: 'PUSH_ADDED_VISITS_SUCCESS',
  PUSH_ADDED_VISITS_FAILURE: 'PUSH_ADDED_VISITS_FAILURE',

  UPDATE_CURRENCY: 'UPDATE_CURRENCY',
  UPDATE_CURRENCY_SUCCESS: 'UPDATE_CURRENCY_SUCCESS',
  RESET_UPDATE_CURRENCY: 'RESET_UPDATE_CURRENCY',

  GET_ALL_SITE_VISITS_REQUEST: 'GET_ALL_SITE_VISITS_REQUEST',
  GET_ALL_SITE_VISITS_SUCCESS: 'GET_ALL_SITE_VISITS_SUCCESS',
  GET_ALL_SITE_VISITS_FAILURE: 'GET_ALL_SITE_VISITS_FAILURE',

  MIGRATE_VISITS_TABLE_DATA_WITH_USED_PENS:
    'MIGRATE_VISITS_TABLE_DATA_WITH_USED_PENS',

  DELETE_VISIT_TABLE_MIGRATION: 'DELETE_VISIT_TABLE_MIGRATION',
};
