export default {
  GET_VISIT_REPORT_REQUEST: 'GET_VISIT_REPORT_REQUEST',
  GET_VISIT_REPORT_SUCCESS: 'GET_VISIT_REPORT_SUCCESS',
  GET_VISIT_REPORT_FAILURE: 'GET_VISIT_REPORT_FAILURE',

  GET_TOOL_DETAILS_REQUEST: 'GET_TOOL_DETAILS_REQUEST',
  GET_TOOL_DETAILS_SUCCESS: 'GET_TOOL_DETAILS_SUCCESS',
  GET_TOOL_DETAILS_FAILURE: 'GET_TOOL_DETAILS_FAILURE',

  UPDATE_ANALYSIS_CATEGORIES: 'UPDATE_ANALYSIS_CATEGORIES',

  UPDATE_SELECTED_PENS: 'UPDATE_SELECTED_PENS',

  UPDATE_SELECTED_ANIMALS: 'UPDATE_SELECTED_ANIMALS',

  ADD_TOOL_IN_VISIT_REPORT_REQUEST: 'SELECT_TOOL_REQUEST',
  ADD_TOOL_IN_VISIT_REPORT_SUCCESS: 'SELECT_TOOL_SUCCESS',
  ADD_TOOL_IN_VISIT_REPORT_FAILURE: 'SELECT_TOOL_FAILURE',

  REMOVE_TOOL_IN_VISIT_REPORT_REQUEST: 'DESELECT_TOOL_REQUEST',
  REMOVE_TOOL_IN_VISIT_REPORT_SUCCESS: 'DESELECT_TOOL_SUCCESS',
  REMOVE_TOOL_IN_VISIT_REPORT_FAILURE: 'DESELECT_TOOL_FAILURE',

  UPDATE_SELECTED_TOOL: 'UPDATE_SELECTED_TOOL',
  UPDATE_SELECTED_TOOL_FAILURE: 'UPDATE_SELECTED_TOOL_FAILURE',

  UPDATE_TOOL_NOTES_VISIT_REPORT_REQUEST:
    'UPDATE_TOOL_NOTES_VISIT_REPORT_REQUEST',
  UPDATE_TOOL_NOTES_VISIT_REPORT_SUCCESS:
    'UPDATE_TOOL_NOTES_VISIT_REPORT_SUCCESS',
  UPDATE_TOOL_NOTES_VISIT_REPORT_FAILURE:
    'UPDATE_TOOL_NOTES_VISIT_REPORT_FAILURE',

  DELETE_TOOL_NOTE_VISIT_REPORT: 'DELETE_TOOL_NOTE_VISIT_REPORT',

  UPDATE_TOOL_IN_VISIT_REPORT: 'UPDATE_TOOL_IN_VISIT_REPORT',

  SHARE_DOWNLOAD_VISIT_REPORT_REQUEST: 'SHARE_VISIT_REPORT',

  SHARE_DOWNLOAD_VISIT_REPORT_FINISH: 'SHARE_DOWNLOAD_VISIT_REPORT_FINISH',

  UPDATE_SELECTED_SITE_DETAILS: 'UPDATE_SELECTED_SITE_DETAILS',

  ADD_COMMENT_REQUEST: 'ADD_COMMENT_REQUEST',
  ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
  ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE',

  DELETE_COMMENT_REQUEST: 'DELETE_COMMENT_REQUEST',
  DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
  DELETE_COMMENT_FAILURE: 'DELETE_COMMENT_FAILURE',

  SELECT_UNSELECT_FORAGE_AUDIT_QUESTION:
    'SELECT_UNSELECT_FORAGE_AUDIT_QUESTION',

  SELECT_UNSELECT_CALF_HEIFER_SCORECARD_QUESTION:
    'SELECT_UNSELECT_CALF_HEIFER_SCORECARD_QUESTION',

  ADD_VISIT_REPORT_DETAILS: 'ADD_VISIT_REPORT_DETAILS',

  PERSIST_NEW_TOOL_IN_VISIT_REPORT: 'PERSIST_NEW_TOOL_IN_VISIT_REPORT',

  SELECT_ALL_TOOLS_REQUEST: 'SELECT_ALL_TOOLS_REQUEST',
  SELECT_ALL_TOOLS_SUCCESS: 'SELECT_ALL_TOOLS_SUCCESS',
  SELECT_ALL_TOOLS_FAILURE: 'SELECT_ALL_TOOLS_FAILURE',

  REMOVE_ALL_SELECTED_TOOLS_VISIT_REPORT:
    'REMOVE_ALL_SELECTED_TOOLS_VISIT_REPORT',

  FORAGE_AUDIT_TOOL_SELECTION_INFO: 'FORAGE_AUDIT_TOOL_SELECTION_INFO',

  HIDE_FORAGE_AUDIT_INFO_ALERT: 'HIDE_FORAGE_AUDIT_INFO_ALERT',

  ADD_NEW_OFFLINE_REPORT_PAGE_REFERENCE:
    'ADD_NEW_OFFLINE_REPORT_PAGE_REFERENCE',

  GENERATE_OFFLINE_VISIT_REPORT: 'GENERATE_OFFLINE_VISIT_REPORT',
  GENERATE_OFFLINE_VISIT_REPORT_FINISH: 'GENERATE_OFFLINE_VISIT_REPORT_FINISH',

  CLEAR_ALL_TOOLS_REFERENCES: 'CLEAR_ALL_TOOLS_REFERENCES',

  SYNC_VISIT_REPORT_SHARE_POINT: 'SYNC_VISIT_REPORT_SHARE_POINT',

  VISIT_REPORT_UPLOADING_FINISH: 'VISIT_REPORT_UPLOADING_FINISH',

  REPORT_UPLOAD_PROGRESS: 'REPORT_UPLOAD_PROGRESS',

  CLEAR_REPORT_PROGRESS: 'CLEAR_REPORT_PROGRESS',

  ADD_SELECTED_VISIT_REPORT_NOTES: 'ADD_SELECTED_VISIT_REPORT_NOTES',
  DELETE_GENERAL_NOTE_VISIT_REPORT: 'DELETE_GENERAL_NOTE_VISIT_REPORT',

  SET_SITE_DETAILS_SELECTED_FOR_VISIT_REPORT:
    'SET_SITE_DETAILS_SELECTED_FOR_VISIT_REPORT',
  SET_ARE_PENS_SELECTED_FOR_VISIT_REPORT:
    'SET_ARE_PENS_SELECTED_FOR_VISIT_REPORT',

  SET_SELECTED_PENS_FOR_VISIT_REPORT: 'SET_SELECTED_PENS_FOR_VISIT_REPORT',

  GET_ALL_SELECTED_PEN_DETAILS_REQUEST: 'GET_ALL_SELECTED_PEN_DETAILS_REQUEST',
  GET_ALL_SELECTED_PEN_DETAILS_SUCCESS: 'GET_ALL_SELECTED_PEN_DETAILS_SUCCESS',
  GET_ALL_SELECTED_PEN_DETAILS_FAILURE: 'GET_ALL_SELECTED_PEN_DETAILS_FAILURE',

  SET_COMMENT_TO_EDIT: 'SET_COMMENT_TO_EDIT',

  CLEAR_VISIT_REPORT_DATA: 'CLEAR_VISIT_REPORT_DATA',
};
